### ISSUE TITLE
[Question] using pc.button inline styling, how to set hover and selected color?

### ISSUE THREAD

**Issue by matt-grain** [pynecone-io/pynecone#100]
Hi,

what are the CSS properties to set the button background hover and active colors ?

````python
    button_style = {
        "color": "black",
        "background": "white",
    }

    return pc.button(
        model.title,
        size="lg",
        on_click=State.switch,
        style=button_style,
        is_active=State.butstate,
    )
````

thanks!

**Comment by Alek99** [comment]
Say you wanted to change the color on the hover you could do something like this

``` python
_hover={"color": "rgb(107,99,246)"},
```

**Comment by matt-grain** [comment]
Thanks (and also for editing!!!!)
Works great, probably something to add in the styling doc!

**Comment by Alek99** [comment]
> Thanks (and also for editing!!!!)
> Works great, probably something to add in the styling doc!

OK awesome, yes will add something about this on the next release of our website

**Comment by FHU-yezi** [comment]
> > Thanks (and also for editing!!!!)
> > Works great, probably something to add in the styling doc!
> 
> OK awesome, yes will add something about this on the next release of our website

By the way, is the website opensource? I'm looking forward to contribute, such as translate our docs to Chinese.
