### ISSUE TITLE
Backend host manually set in dev mode

### ISSUE THREAD

**Issue by obronco** [pynecone-io/pynecone#1017]
To make the backend work when accessing from a remote machine in dev mode, it was necessary to manually set the backend IP.

In pcconfig.py, first line after import pynecone as pc:

pc.constants.BACKEND_HOST = 'xxx.xxx.xxx.xxx'   # host IP

**Comment by obronco** [comment]
Setting the api_url app config parameter wasn´t enough to make it work.

**Comment by ElijahAhianyo** [comment]
> Setting the api_url app config parameter wasn´t enough to make it work.

Not sure if I understand you correctly, is there an error you face when you set api_url to a remote ip?

**Comment by obronco** [comment]
To get the frontend to work when accessing the dev deployment from a different machine in the network, I had to set the BACKEND_HOST constant manually:

import pynecone as pc

pc.constants.BACKEND_HOST = '192.168.20.99'

class MyConfig(pc.Config):
    pass

config = MyConfig(
    app_name="my_app",
    db_url="sqlite:///pynecone.db",
    env=pc.Env.DEV,
    api_url='http://192.168.20.99:8000',
    cors_allowed_origins=[pc.constants.CORS_ALLOWED_ORIGINS],
)
