### ISSUE TITLE
How to set datatable's th text-align=center?

### ISSUE THREAD

**Issue by evandeng2009** [pynecone-io/pynecone#1020]
**Describe the bug**
Datatable does not set the th center, then how to do that?
Tried but not work:
pc.DataTable: {
        # or text-align or align
        "text_align": "center"
    }

By the way,  where can I see a list of css attributes of those components? Otherwise , seems like have to guess and try.

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.7
 - Pynecone Version: 0.1.29
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by Lendemor** [comment]
There is no restriction when it come to css attributes.
When you use a component, it will recognize the specific arg that are defined for it, and anything else will be treated as a css property.

Can you show a minimal snippet of your code, as well as tell us which cell of the datatable do you expect to be centered ?

**Comment by evandeng2009** [comment]
This is my case:

1. Problem 1: pc.data_table width will change from time to time when the content changes, although I do set specific width with pc.Datatable width in page style arg(This is global css settings I mean in the following).

2. So I created a table, use pc.foreach to manually generate th and td, as global css width of table works.

3. Problem 2: However, th of both pc.data_table and generated one do not have content aligned center by default,  just like html th, as well as font weight.

4. Problem 3:  By the way, no place to set font size for pc.data_table th, besides, th's font_family is different from global settings. And generated th or th does not inherit the attributes of global css settings except font_size and font_family, for example, border_width, padding and margin.

5. Then I put an inline style in generated th and td, it works.

Another probem I'v found is css arg name is not unified. Somewhere in Docs examples it is h, and somewhere height for instance, and color vs color_scheme.

**Comment by programmeddeath1** [comment]
@evandeng2009 Hi can you tell me how did you add inline style to the th and td? which file would i need to make the changes to
