### ISSUE TITLE
Add autofoucs to input component

### ISSUE THREAD

**Issue by evandeng2009** [pynecone-io/pynecone#1028]
**Describe the bug**
Add autofoucs to input component, so no need to click when the page loads.

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:
 - Pynecone Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by Lendemor** [comment]
Will take a look at this.
