### ISSUE TITLE
NumberInput is broken: TypeError: _e.preventDefault is not a function

### ISSUE THREAD

**Issue by masenf** [pynecone-io/pynecone#1034]
**Describe the bug**

`NumberInput` doesn't work with `on_change` anymore.

**To Reproduce**

```python
import pynecone as pc

class State(pc.State):
    v: int


def index() -> pc.Component:
    return pc.center(
        pc.number_input(
            value=State.v,
            on_change=State.set_v,
        ),
        padding_top="10%",
    )


app = pc.App(state=State)
app.add_page(index)
app.compile()
```

**Expected behavior**

`v` is updated as the user types a valid number

**Screenshots**

<img width="730" alt="image" src="https://github.com/pynecone-io/pynecone/assets/1524005/29edf6b2-e5d7-494e-81cd-049e88bf7ce6">

```
Unhandled Runtime Error
TypeError: _e.preventDefault is not a function
```

```
pages/index.js (23:11) @ preventDefault

  21 | const Event = (events, _e) => {
  22 |     if (_e) {
> 23 |       _e.preventDefault();
     |         ^
  24 |     }
  25 |     setState({
  26 |       ...state,
```

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 98f1b30735701af3f97a0b7b894eb8c03ab290fc 
 - OS: macOS 3.3.1
 - Browser (Optional): Firefox, Safari
 
**Additional context**

@picklelo Seems introduced by a recent change #1031.

With 0.1.29, it is working as expected.

**Comment by picklelo** [comment]
@masenf thanks for catching this! Just put up a fix
