### ISSUE TITLE
Passing strings to event handler functions via lambda

### ISSUE THREAD

**Issue by paul-sx** [pynecone-io/pynecone#104]
**Describe the bug**
Using a lambda function to bundle args to an event handler function works if the args are numbers, but not if they are strings

**To Reproduce**
The code 
```python
pc.button("STOP", on_click=lambda: State.status_change(index, "stop"))
```
Compiles the string literal to a bareword in the javascript:
```jsx
<Button onClick={() => Event([E("state.status_change", {index:0,change:stop})])}>
{`STOP`}</Button>
```
This causes an error as the event payload is not transmitted properly
```
Traceback (most recent call last):
  File "/home/p/.asdf/installs/python/3.10.6/lib/python3.10/site-packages/pynecone/state.py", line 357, in process
    events = fn(**event.payload)
TypeError: State.status_change() missing 1 required positional argument: 'change'
```
The state function is
```python
def status_change(self, index, change):
        self.services[index].status = change
        self.services = self.services
```

**Expected behavior**
It would be expected to compile to the following Javascript
```jsx
<Button onClick={() => Event([E("state.status_change", {index:0,change:"stop"})])}>
{`STOP`}</Button>
```
The offending code is likely in pynecone/utils.py at
```python
def format_event(event_spec: EventSpec) -> str:
    """Format an event.
    Args:
        event_spec: The event to format.
    Returns:
        The compiled event.
    """
    args = ",".join([":".join((name, val)) for name, val in event_spec.args])
    return f"E(\"{format_event_fn(event_spec.handler.fn)}\", {wrap(args, '{')})"
```
I think val needs to be wrapped and escaped if it is a string

** Specifics (please complete the following information):**
 - Python Version: 3.10.6
 - Pynecone Version: pynecone-io==0.1.8
 - OS: Ubuntu 22.04
 - Browser (Optional):

**Comment by picklelo** [comment]
Thanks for catching! And for pointing out the offending code, we're working on a fix asap.

**Comment by Alek99** [comment]
Good timing I actually came across this same error a couple of minutes ago here https://github.com/pynecone-io/pynecone/issues/103. We are currently work on this fix
