### ISSUE TITLE
Highlight Component

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#1048]
Create a highlight component for Pynecone. This should be a fairly straightforward component as it follow a lot of the chakra components we use.

Great first issue for new contributors!

https://chakra-ui.com/docs/components/highlight

**Comment by Unknownsentinel193** [comment]
Hi, could please you assign this to me, i would like to do it

**Comment by Lendemor** [comment]
Thanks for considering it.

Don't hesitate to drop by our Discord if you want to further discuss this issue.

**Comment by Alek99** [comment]
Hi are you currently working on this another person is wondering if they can take this issue on

**Comment by Unknownsentinel193** [comment]
Im currently working it.

**Comment by Unknownsentinel193** [comment]
There is already a highlight.py in the typography folder, should edit that, or create a new one?

**Comment by TaiJuWu** [comment]
I've done the component. May I open a PR?

**Comment by TaiJuWu** [comment]
I've done the component. May I open a PR?

**Comment by TaiJuWu** [comment]
May I open a PR for this component?

**Comment by Unknownsentinel193** [comment]
Sure, if you made the component

**Comment by TaiJuWu** [comment]
@Unknownsentinel193 Thanks your reply.

**Comment by Alek99** [comment]
Ok nice re assigning to @TaiJuWu
