### ISSUE TITLE
Add Chakra Tag component

### ISSUE THREAD

**Issue by iron3oxide** [pynecone-io/pynecone#1049]
It would be nice to be able to use the [Chakra tag component](https://chakra-ui.com/docs/components/tag/usage) in pynecone. This would mean wrapping `Tag`, `TagLabel`, `TagLeftIcon`, `TagRightIcon` and `TagCloseButton`. Should be an easy addition.

**Comment by Unknownsentinel193** [comment]
Hi, could please you assign this to me, i would like to do it
