### ISSUE TITLE
How can I add new attributes to html tags?

### ISSUE THREAD

**Issue by pritam-dey3** [pynecone-io/pynecone#1072]
I am trying to use this [scrollspy](https://www.npmjs.com/package/react-ui-scrollspy) component. Which requires me to add "data-to-scrollspy-id" attribute to `<p>` tags. I tried to subclass `Text` with `data_to_scrollspy_id` variable, but it is throwing me the following error: 
```
pydantic.error_wrappers.ValidationError: 1 validation error for SectionText
spyid
  instance of _GenericAlias expected (type=type_error.arbitrary_type; expected_arbitrary_type=_GenericAlias)
```
I am not familiar with react or Typescript, what can I do?

**Comment by TaiJuWu** [comment]
It seems to not offer this feature right now.
Maybe It can work in the future.

**Comment by TaiJuWu** [comment]
It seem to not support custom attribute right now.

**Comment by pritam-dey3** [comment]
Can this be supported somehow? I have currently handled this with `pc.html("<p data-to-scrollspy-id> text </p>")`.

**Comment by TaiJuWu** [comment]
I’ve open a PR #1085 .
Maybe you can try it.

**Comment by pritam-dey3** [comment]
The PR fixes it
