### ISSUE TITLE
Bump pydantic to 1.10.6

### ISSUE THREAD

**Issue by TudorAndrei-Pythia** [pynecone-io/pynecone#1074]
**Describe the bug**
I need to use  [Surrealdb.py](https://github.com/surrealdb/surrealdb.py) in my pynecone app, and there is a missmatch of pydantic versions. 

**Additional context**
[Surrealdb.py pydantic version](https://github.com/surrealdb/surrealdb.py/blob/697f0e552a5d8238d1ac9e545fe84fa1ff1ac0d4/pyproject.toml#L27) is >= 1.10.6 and pynecone's pydantic is == 1.10.2

**Comment by picklelo** [comment]
Sorry, looks like I forgot to include the `^` in the toml, updating this now
