### ISSUE TITLE
Make fault easily when everytime create a new example code with the unexpected .gitignore file from pc init

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone#1086]
**Describe the bug**
That's very hard to management example code for using the current .gitignore  by pc init
We must support `pc init --no-cache` , `pc init --pure-source-on-git` or `pc init --psog`
or github will become messy by the Pynecone app. 

Every time push the wrong code because I forget to change .gitignore by hand. 
But I'm busy making example code and testing the API, so I need to .gitngore correct. 
nobody want to push __pycache__ go on the github. 
Some developer prefer to put the clean code on the github... not compiled byte code. 

But right now, we don't have this solution the help. 

So we need to some command like `pc init --no-cache`, `pc init --pure-source-on-git` or `pc init --psog`

**To Reproduce**
pc init

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:  NA
 - Pynecone Version: NA
 - OS:  NA
 - Browser (Optional): NA
 
**Additional context**

**Comment by milochen0418** [comment]
After communication, we have the summmary.  
--
In the discord #opensource channel, there is a discuss about this PR. 
Because there are at least 3 .gitignore files in the pynecone app project 
- app's root
- app (python part named as app_name you set in pc init)
- web (web part   named as .web)
After discussion and understanding, I explain what happened in the discord channel. 

.gitignore will influent each other .gitignore. The core team needs to think about how to manage them to get the most flexibility first. And then we can start to think what to do next.  
In the future, the solution maybe is the copying some .gitignore file to the app's root, or support some other thing to solve.  Or some other way else.

**Comment by Lendemor** [comment]
I think this issue can be closed due to your other PR having been merged.

Can you confirm ?

**Comment by milochen0418** [comment]
Close this PR because of this 
- https://github.com/pynecone-io/pynecone/pull/718
