### ISSUE TITLE
Feature Request: Provide a /health check endpoint on the backend

### ISSUE THREAD

**Issue by jdoss** [pynecone-io/pynecone#1090]
**Describe the Feature Request**
It would be nice to have a default URL of `/health` return a 200 if the backend is healthy and online. Currently, if you curl the backend it only produces a 404 on `/health` unless you add one in yourself.

**Expected behavior**
When running Pynecone in production, it would be nice to health check the backend on `/health` in order to generate a 200 response to use a health check to ensure it is online.

We can healthcheck the frontend on `/` because it responds with a 200 when it is online.

```
$ curl -I localhost:8000/health
HTTP/1.1 200 OK
date: Fri, 26 May 2023 17:57:00 GMT
server: uvicorn
content-length: 22
content-type: application/json
```

**Comment by jdoss** [comment]
Oh nice! It does respond to requests, but it looks like it doesn't generate a 200 response but instead a 405.

```
$ curl localhost:8555/ping
"pong"

$ curl -I localhost:8555/ping
HTTP/1.1 405 Method Not Allowed
date: Fri, 26 May 2023 18:30:48 GMT
server: uvicorn
allow: GET
content-length: 31
content-type: application/json
```

**Comment by picklelo** [comment]
Hmm I think it may not be doing a GET request in your second one. This works for me:

```bash
$ curl -X GET -I localhost:8000/ping
HTTP/1.1 200 OK
date: Fri, 26 May 2023 18:36:57 GMT
server: uvicorn
content-length: 6
content-type: application/json
```

**Comment by jdoss** [comment]
Woops! You are right!

```
$ curl -X GET -I localhost:8555/ping
HTTP/1.1 200 OK
date: Fri, 26 May 2023 18:39:06 GMT
server: uvicorn
content-length: 6
content-type: application/json
```
