### ISSUE TITLE
Don't let pc.form submit reload page

### ISSUE THREAD

**Issue by evandeng2009** [pynecone-io/pynecone#1101]
**Describe the bug**
pc.form on_submit will reload entire page when enter pressed or click button, meanwhile, keyword in pc.input will disapper(although default_value can get it back), this is not a good idea. Make it submit in the backend please or add an additional option.

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.7
 - Pynecone Version: 0.1.31
 - OS: Windows
 - Browser (Optional):
 
**Additional context**

**Comment by Alek99** [comment]
Can you try upgrading to 0.1.32 this should be fixed

**Comment by evandeng2009** [comment]
Yes, version 0.1.32 works. 

And [Updating App] Applying changes and refreshing. Time: 2023-05-30 12:45:08.096602 tips looks better. Thank you.
