### ISSUE TITLE
Where can I put Google analyse Javascript code?

### ISSUE THREAD

**Issue by evandeng2009** [pynecone-io/pynecone#1103]
**Describe the bug**
Where can I put Google analyse Javascript code? pc.html seems not possible.

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:
 - Pynecone Version: 0.1.32
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by jiangmiemie** [comment]
that is my website   : https://github.com/jiangmiemie/PyneconeBlog
![image](https://github.com/pynecone-io/pynecone/assets/69161207/2855174e-cdce-42d2-8f55-74b7e075e1ec)
![image](https://github.com/pynecone-io/pynecone/assets/69161207/f930cb9b-81dd-481b-b5ff-c09723779002)

**Comment by evandeng2009** [comment]
Yeah, it works. Thank you @jiangmiemie 

 I did not find any usage info for script_tags except app.add_page method. And an attention here: JS code requires single quotes, double quotes will throw exceptions.
