### ISSUE TITLE
Does pc.cond support more func to process the comparison?

### ISSUE THREAD

**Issue by evandeng2009** [pynecone-io/pynecone#1105]
**Describe the bug**
I need to apply some simple func like str.split() and list index to firstly process the value transfered to it, and then do a comparsion. Or any other approach is also appreciated.

e.g: The pc.foreach sends a value to this func below,
def a_func(value):
	return pc.cond(
            value.split(",")[0] == "0",
            pc.td(pc.icon(tag="arrow_up")),
            pc.td(pc.icon(tag="download"))
        )

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:
 - Pynecone Version: 0.1.32
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by Lendemor** [comment]
If you have some complex logic for `pc.cond`, you should consider defining a computed var and pass this var as the condition to `pc.cond`

**Comment by evandeng2009** [comment]
Case is:
I get some data(list[str], as a var) from database, and sent to pc.foreach which calls the func defined above, the func calls pc.cond to check if part of the value is equal to something.

**Comment by evandeng2009** [comment]
Finally I found a work around. My use case is to check the value of first field and then show something different(as above, up arrow or download icon) and meanwhile, directly refer to second field value.

At the very beginning, I combine those values of 2 fields together hoping for splitting them which was confirmed not possible. Thanks to https://github.com/pynecone-io/pynecone/pull/1029 which inspired me, so I append second field value to the list of first field. Therefore, judgement on first element of this list, and use second one. Problem fixed. 

Use list[dict[str,list[str]]] is more functional than list[list[list[str]]] as we can use item[0] for access to key(be aware of what the key is), for my case, instead of using index.

**Comment by evandeng2009** [comment]
Finally I found a work around. My use case is to check the value of first field and then show something different(as above, up arrow or download icon) and meanwhile, directly refer to second field value.

At the very beginning, I combine those values of 2 fields together hoping for splitting them which was confirmed not possible. Thanks to https://github.com/pynecone-io/pynecone/pull/1029 which inspired me, so I append second field value to the list of first field. Therefore, judgement on first element of this list, and use second one. Problem fixed. 

Use list[dict[str,list[str]]] is more functional than list[list[list[str]]] as we can use item[0] for access to key(be aware of what the key is), for my case, instead of using index.
