### ISSUE TITLE
Link(pc.link) href does not track dynamic state variable

### ISSUE THREAD

**Issue by hsol** [pynecone-io/pynecone#1106]
**Describe the bug**
Link(pc.link) href does not track dynamic state variable.

**To Reproduce**
1. Make some var on State
2. Put State var on href attribute of pc.link

**Expected behavior**
a tag href will change and move to dynamic link when user clicked.

**Screenshots**
<img width="1486" alt="image" src="https://github.com/pynecone-io/pynecone/assets/1524891/f7cbe5f3-979f-46cc-a17a-29f087ce4e16">

**Specifics (please complete the following information):**
 - Python Version: 3.10
 - Pynecone Version: 0.1.29
 - OS: macOS intel
 - Browser (Optional): Chrome 113.0.5672.126
 
**Additional context**

Not only a tag but also the argument of `on_click` behaving differently than expected. This phenomenon exists quite a bit.

**Comment by masenf** [comment]
Have you tried something like `State.foo["id"].to(str)`?

It looks like pynecone cannot determine the type of the value being extracted from the dict. Using a TypedDict might also work.

Without example code, it's harder to say where things might be going wrong.

**Comment by hsol** [comment]
Wow you solved my problem!! @masenf .
Thanks you so much to(str) works for me but TypedDict not worked.
