### ISSUE TITLE
Add multithreading to compiler

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#1133]
Currently the compile process is done in a[ single thread](https://github.com/pynecone-io/pynecone/blob/main/pynecone/app.py#LL412C11-L412C11). We can speed this up by using multithreading to compile the app pages in parallel.

**Comment by jonathanalvares9009** [comment]
- [ ] Install `Pyncone` locally
- [ ] Learn how to build a basic app
- [ ] Learn how the compile process works
- [ ] Make the compile process Muti threaded
