### ISSUE TITLE
link - is_external is not working

### ISSUE THREAD

**Issue by LayGPark** [pynecone-io/pynecone#1135]
**Describe the bug**
is_external is not working at link.
exist or not, same.

**To Reproduce**
 - Code/Link to Repo: https://github.com/pynecone-io/pynecone-examples/tree/main/crm
 - https://github.com/pynecone-io/pynecone-examples/blob/849351687aff0c2325523540289a481a0fcc6cce/crm/crm/pages/index.py#L18

**Expected behavior**

**Screenshots**
<img width="596" alt="image" src="https://github.com/pynecone-io/pynecone/assets/13059827/31c7fe52-e2cb-45d1-b760-626f454acac8">
```
                pc.link(
                    pc.button(
                        "Log in to get started", color_scheme="blue", underline="none"
                    ),
                    href="/login",
                    is_external=True,
                ),
```

** Specifics (please complete the following information):**
 - Python Version: Python 3.10.6 - virtualenv
 - Pynecone Version: 0.1.32
 - OS:  docker container
```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```
 - Browser (Optional): whale(crhomium base), safari
 
**Additional context**

**Comment by masenf** [comment]
@LayGPark what are you expecting it to do? according to the docs for `is_external` "If true, the link will open in new tab."

In my experiments, the link is not opening in a new tab... and I'm actually having trouble even finding a successful next.js snippet that causes a link to open in a new tab.

**Comment by LayGPark** [comment]
@masenf  thank you for your answer!
yes, I want to 'open in new tab'

you means this problem is not cause of pyncone, right?

**Comment by masenf** [comment]
@LayGPark No, this turned out to be a compatibility issue from when pynecone upgraded to Next 13.

I have posted a patch with the fix: https://github.com/pynecone-io/pynecone/pull/1138

You can test if it is working in your environment.

**Comment by LayGPark** [comment]
@masenf Ah, ok!
Thank you!
I'll try after release https://github.com/pynecone-io/pynecone/pull/1138 :)
