### ISSUE TITLE
Feature Request: Highcharts

### ISSUE THREAD

**Issue by bkxndata** [pynecone-io/pynecone#114]
I was wondering if there were any plans to integrate highcharts (highcharts.com) to make the front end graphing / dashboarding capabilities more dynamic and aesthetically pleasing  

justpy has attempted to do so, so curious if it was possible for pynecone as well ([example here](http://q.bitplan.com:10008/))

also R has a pretty slick package called [highcharter](https://jkunst.com/highcharter/)

feel like this could really differentiate pynecone from competitors as highcharts > plotly

**Comment by Alek99** [comment]
Yes definitely can add! I'lllook into this

**Comment by bkxndata** [comment]
incredible

**Comment by Alek99** [comment]
Im looking into implementing highchairs this week there license is not a standard MIT or Apache license so not sure if I can incorporate this

**Comment by Alek99** [comment]
Yeah its only free for personal use so im not sure if we can actually incorporate it

**Comment by bkxndata** [comment]
Weird – curious how R and JustPy were able to implement it

Don’t really have a huge affinity to any library, just think plotly is pretty horrible (visually unappealing for a javascript library).


[cid:xn_black_6a709d45-eaf2-4476-b50f-244d6d5fb595.png]
Bryan Kaufman
412 West 15th Street
13th Floor
New York, NY 10011
o: 646-849-0533
