### ISSUE TITLE
pc.link not work when there is no href in it

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone#1160]
**Describe the bug**
When use the link like the following, there will be a error page as the following
```python 
pc.link("https://reactjs.org/docs/fragments.html"),
```
And the root cause is because there is no href in pc.link. 
<img width="998" alt="Screenshot 2023-06-07 at 10 41 51 PM" src="https://github.com/pynecone-io/pynecone/assets/12568287/5a46dbb7-798b-4ada-846c-5add9d5103de">

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:
 - Pynecone Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by TaiJuWu** [comment]
You should use
pc.link(href="https://reactjs.org/docs/fragments.html"),

**Comment by milochen0418** [comment]
@TaiJuWu The current examples code and the project made by another people may use pc.link("https://reactjs.org/docs/fragments.html")
