### ISSUE TITLE
on_load is incompatible with pc.redirect

### ISSUE THREAD

**Issue by TaiJuWu** [pynecone-io/pynecone#1165]
**Describe the bug**

I try to run below code in app.py
```python
self.add_page(
            Fragment(),
            route=f"{download_url}",
            on_load=redirect(config.api_url + "/" + f"{download_url}"),
        )
```
It will cause 
```
/Users/tai-juwu/ws/pynecone/pynecone/app.py:348:21 - error: Argument of type "EventSpec" cannot be assigned to parameter "on_load" of type "EventHandler | List[EventHandler] | None" in function "add_page"
    Type "EventSpec" cannot be assigned to type "EventHandler | List[EventHandler] | None"
      "EventSpec" is incompatible with "EventHandler"
      "EventSpec" is incompatible with "List[EventHandler]"
      Type cannot be assigned to type "None" (reportGeneralTypeIssues)
```
Is it normal?  on_load should be allowed EventSpec?

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**
The code is executed as my excepted. 
But there is a pyright error message.
The error message should be reviewed.

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:
 - Pynecone Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by Alek99** [comment]
Are you using pc.redirect? What is redirect here?

**Comment by TaiJuWu** [comment]
> Are you using pc.redirect? What is redirect here?

Yes, I use pc.redirect.
Redirect from frontend to backend.

I found pc.redirect return EventSpec and on_load only accepts Event_handler.
