### ISSUE TITLE
Can't get the domain of the site

### ISSUE THREAD

**Issue by jq6l43d1** [pynecone-io/pynecone#1174]
I have a website that I run locally and on two different domains. I have a few lines of code that I have to change manually for each deployment. It would be great if there was a way to get the domain of the url with code. I checked in state.py [](https://github.com/pynecone-io/pynecone/blob/ee762a7b35aad60b79c45bbf856b86feb9973c14/pynecone/state.py#L459) but I didn't see anything that would help me get the current domain. I think it would be great if there was a get_domain function added to state.py.

**Comment by Lendemor** [comment]
`pc.State` offers the method `get_headers()` that give you lot of metadata in the form of a dict.
Inside this `dict`  you can query the key `host` and/or `origin`.
