### ISSUE TITLE
Accordion doesn't re-collapse unless allow_multiple=True

### ISSUE THREAD

**Issue by simonmesmith** [pynecone-io/pynecone#1201]
**Describe the bug**
If you use the Accordion component without setting `allow_multiple=True`, even if you only have one item, you can open it but it won't collapse again when you click it. You can see this for yourself in the documentation: https://pynecone.io/docs/library/disclosure/accordion

**To Reproduce**
 - Create an Accordion
 - Don't include `allow_multiple=True`
 - Click to open the Accordion; it opens
 - Click to close it; it doesn't close
 - Set `allow_multiple=True`
 - Repeat the process and it will work

**Expected behavior**
Accordion should both open and close without needing to specify `allow_multiple=True`.

**Screenshots**
Just go to https://pynecone.io/docs/library/disclosure/accordion.

**Specifics:**
 - Python Version: 3.11.4
 - Pynecone Version: 0.1.33
 - OS: MacOS Ventura 13.4
 - Browser (Optional): Chrome 114.0.5735.106

**Comment by Lendemor** [comment]
Did you use `allow_toggle` if you are omitting `allow_multiple` ? 
If not, then this is normal behaviour.

**Comment by simonmesmith** [comment]
Ah, it would indeed seem that this was the issue and I should have read the documentation more closely.

Unless my read of the code history is wrong, it looks like the default for allow_toggle used to be True and was very recently switched.

I had repurposed some code and when it wasn't working assumed there was a bug. Sorry for the fire drill.

**Comment by Lendemor** [comment]
Yeah we had to put a fix recently because using `allow_multiple` was conflicting with allow_toggle and triggering lot of warning in the console on frontend.
