### ISSUE TITLE
Investigate NextJS API routes

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#121]
We may be able to use [api routes](https://nextjs.org/docs/api-routes/introduction) to forward requests to the FastAPI server. See: https://github.com/pynecone-io/pynecone/discussions/120

**Comment by matt-grain** [comment]
As it looks like there is only 2 APIs: `/event` and `/ping` to forward requests to, I guess that's not too complicated. But as right now you generate the next.js static website, the way to run the frontend will be a little different.

If I can help or test, tell me!

**Comment by picklelo** [comment]
Ah I see, so the api routes may only work in dev mode, where we don’t do the static site generation.

If you have time and want to try to add this soon, I can help give guidance. Otherwise, we will definitely try to include this in an upcoming milestone.

**Comment by matt-grain** [comment]
I won't say at all that I'm a next.js expert (else I would probably not use Pynecode.io :D) but I played a little with next.js serverside capabilities, so yes I'll post here some examples, resources or whatever with pleasure. But in brief, yes it means to do not export the static website but to run a node.js server.

**Comment by picklelo** [comment]
Awesome, I'll look into it too, I'm adding it to the next milestone

**Comment by matt-grain** [comment]
**Disclaimer**, if this is only to decouple the frontend and the python backend, using next.js serverside capabilty is probably overkill. I`m pretty sure that's doable using nginx and some good url redirection (to rewrite /api:3000 to /api:8000).

But, if you start to use next.js serverside capabilities, I guess it will help to simplify your python to typescript engine and you will be able to generate typescript on the fly (thru next.js SSR) as the frontend won`t be static anymore. 

So, a little early to say but I`m pretty sure it will open a lot of cool stuff for pyncone.io :)

Some links I found interesting:

next.js serverside capabilities:
- https://medium.com/weekly-webtips/next-js-on-the-server-side-notes-to-self-e2170dc331ff
- https://medium.com/swlh/server-side-rendering-with-next-js-56f84f98f9bd
- https://javascript.plainenglish.io/what-is-next-js-and-server-side-rendering-9e24ea21c144
- https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props

next.js API routes concept:
- https://nextjs.org/docs/api-routes/introduction
- https://nextjs.org/learn/basics/api-routes/creating-api-routes
- https://refine.dev/blog/next-js-api-routes/

Deployment:
- https://dev.to/scaledynamics/deploy-a-nextjs-ssr-application-42gm
- Using Azure SWA hybrid deployment: https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid (note: npm run dev to start the server)

**Comment by FHU-yezi** [comment]
Needn't to host frontend with Node.js at all, just export the files and host it  by Nginx.

**Comment by matt-grain** [comment]
To be challenged:

Using next.js API routes and other SSR capabilities:

| **Pros**                                                                                                   | **Cons**                                                                       |
|------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
| Hide the FastAPI backend / avoid CORS issues                                                               | Requires a node.js (or equivalent) server to implement the API routes          |
| Supports SSR and dynamic generation of HTML/JS content based on python code                                | Somewhat redudant with the FastAPI api dedicated to the frontend communication |
| Simplify future auth needs required at the frontend layer using NextAuth.js                                | Creates a dependence on next.js server side                                    |
| Possible performance improvement by providing caching when accessing the FastAPI backend may be not needed | One more layer, performance impact?                                            |
|                                                                                                            |                                                                                |

Using nginx to proxify FastAPI:

| **Pros**                   | **Cons**                                        |
|----------------------------|-------------------------------------------------|
| Pretty proven and standard | Limited to API proxification, no other values   |
| Light                      | Cannot support next.js server-side capabilities |
|                            |                                                 |

**Comment by picklelo** [comment]
@matt-grain awesome writeup! 

I didn't know about NextAuth.js that looks interesting - we're trying to add some sort of auth into Pynecone soon. In the upcoming release, we're moving to use Websockets for communication, I'm not sure how that will affect things. I think we won't see much benefit from the API caching after this change.

The solution we're planning to use for `pc deploy` is similar to the second way:
* We run `next export` in the `.web` directory to generate a static build
* We upload this to a public S3 bucket to host the frontend (and put Cloudfront in front of it)
* Then on a server, we run only the backend using `pc run --env prod --no-frontend`

This seems to work pretty well, you can use NGINX or anything to serve the frontend. You just have to make sure the backend url is compiled into the code, so it connects to the correct server for sending events.

**Comment by picklelo** [comment]
We're using websockets now, so I don't think we can do this. We can re-open this if people want it and there is a good workaround.

**Comment by zalo** [comment]
Though it's late, I wanted to mention one of the nice benefits of single-port exposure is there's a nice 1-liner for exposing a local app to the internet for development (via [flask-cloudflared](https://github.com/UWUplus/flask-cloudflared)):
```python
import flask_cloudflared; ext_url = flask_cloudflared._run_cloudflared(port=8000); print(f" * Running on {ext_url}")
```

(Though, perhaps a modification to `flask-cloudflared` could allow it to expose a set of ports instead of just one...)
