### ISSUE TITLE
This request has been blocked; this endpoint must be available over WSS

### ISSUE THREAD

**Issue by bbreton3** [pynecone-io/pynecone#1212]
**Describe the bug**
I am trying to deploy the backend to CloudRun with HTTPS.
I configured https and wss adresse in the env.json file, but there is a piece of code in the `constant.py` that rewrites the `wss://` into `ws://`

**Expected behavior**
The page should load, but any call to the websocket doesn't go thought and sends the error.

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.10
 - Pynecone Version: 0.1.32
 - OS: Docker
 - Browser (Optional): Chrome
 
The code is on line 201 in file constant.py

```python
class Endpoint(Enum):
    """Endpoints for the pynecone backend API."""

    PING = "ping"
    EVENT = "event"
    UPLOAD = "upload"

    def __str__(self) -> str:
        """Get the string representation of the endpoint.

        Returns:
            The path for the endpoint.
        """
        return f"/{self.value}"

    def get_url(self) -> str:
        """Get the URL for the endpoint.

        Returns:
            The full URL for the endpoint.
        """
        # Import here to avoid circular imports.
        from pynecone.config import get_config

        # Get the API URL from the config.
        config = get_config()
        url = "".join([config.api_url, str(self)])

        # The event endpoint is a websocket.
        if self == Endpoint.EVENT:
            # Replace the protocol with ws.
            url = url.replace("https://", "wss://").replace("http://", "ws://")

        # Return the url.
        return url
```

**Comment by bbreton3** [comment]
It has worked, thank you @ElijahAhianyo ❤️

**Comment by topkek-issou** [comment]
Hey @bbreton3
How did you determine the `api_url` you had to set in CloudRun ?
Did you use nginx / supervisor to redirect port 8000 to the default 8080 port of CloudRun ?
