### ISSUE TITLE
Custom ModelView configuration in the Admin

### ISSUE THREAD

**Issue by siddhantgoel** [pynecone-io/pynecone#1224]
**Describe the bug**
When using the admin dashboard, the `setup_admin_dash` method uses the `ModelView` class for all registered models.

This makes it hard to assign custom `ModelView` configurations as documented [here](https://jowilf.github.io/starlette-admin/tutorial/configurations/modelview/). This would be especially useful if, for instance, we would want to hide specific columns from the admin, or adjust which fields are searchable on.

**To Reproduce**
1. Set up any admin as per the instructions at https://github.com/pynecone-io/pynecone/pull/1098#issuecomment-1570433037
2. Open up the admin at http://localhost:8000/admin

**Expected behavior**
The expected behavior would be that we can assign custom `ModelView` classes to specific models when registering them for the admin dashboard.

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 0.1.34
 - OS: macOS
 - Browser (Optional): Firefox
 
**Additional context**
One proposal for how such an API could look like:

```python
config = pc.Config(
    app_name="example",
    db_url="sqlite:///pynecone.db",
    enable_admin=True,
    admin_dash=pc.AdminDash(
        models=[User, Question],
        model_view_overrides={
            User: CustomUserView,
        },
    ),
    env=pc.Env.DEV,
)
```

**Comment by Lendemor** [comment]
The usage of starlette-admin (while useful) is not intended as the definitive go-to for admin management of models.

We intend to have a admin system that work fully in pynecone, we just haven't gotten to make it. (and there are more pressing things to solve first).

So I don't think we will invest time to improve the current system. 
(Of course, if someone open a PR that resolve this problem, we will consider it and review it).

**Comment by siddhantgoel** [comment]
I can submit a patch for this. Would you prefer the `model_view_overrides` parameter or a different interface?

**Comment by Lendemor** [comment]
`model_view_overrides` seems fine :+1:
