### ISSUE TITLE
socket error and consuming server CPU 100%

### ISSUE THREAD

**Issue by DongyoungKim2** [pynecone-io/pynecone#1233]
**Describe the bug**

I created a website using pynecone last April, and so far works file. 
After updating pynecone version 0.1.33 /0.1.34 recently, following error occurs (sorry I do not remember what version I was )

error with following message, consuming server CPU 100% (one core).  and backend doesn't work (frontend is still working)
it does not happen at the start. After a while, it goes like this. there is no variable named "fileno" in my code. 

```
AttributeError: 'NoneType' object has no attribute 'fileno'
Exception in callback BaseSelectorEventLoop._start_serving(functools.par...7fe2345dbf40>), <gunicorn.soc...x7fe23a208b20>, None, <Server sockets=()>, 2048, None)
handle: <TimerHandle when=4846977.216531518 BaseSelectorEventLoop._start_serving(functools.par...7fe2345dbf40>), <gunicorn.soc...x7fe23a208b20>, None, <Server sockets=()>, 2048, None)>
Traceback (most recent call last):
  File "/home/azureuser/anaconda3/envs/pc/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/azureuser/anaconda3/envs/pc/lib/python3.10/asyncio/selector_events.py", line 145, in _start_serving
    self._add_reader(sock.fileno(), self._accept_connection,
  File "/home/azureuser/anaconda3/envs/pc/lib/python3.10/site-packages/gunicorn/sock.py", line 37, in __getattr__
    return getattr(self.sock, name)
```
Anybody knows what is happening here?

**To Reproduce**
 - Code/Link to Repo: sorry, this is private repo

**Expected behavior**

**Screenshots**
<img width="892" alt="Screenshot 2023-06-23 at 6 02 33 PM" src="https://github.com/pynecone-io/pynecone/assets/32670163/522d49cb-7028-4a99-8404-23d67ae05989">

** Specifics (please complete the following information):**
 - Python Version: 3.10
 - Pynecone Version: 0.1.34
 - OS: ubuntu 20.04
 - Browser (Optional): chrome
 
**Additional context**

**Comment by Lendemor** [comment]
Hello,
I haven't seen that error so far.

Assuming you are hosting your site somewhere, do you have the error in both prod mode and in local dev? 

Could you try to isolate a minimal working example that trigger your problem?

**Comment by DongyoungKim2** [comment]
This error occurs during prod. I'm looking for what is triggering this error and let you know. Thanks!

**Comment by DongyoungKim2** [comment]
I tried few things and got following error. I
```sh
socket.accept() out of system resource
socket: <asyncio.TransportSocket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('0.0.0.0', 8000)>
Traceback (most recent call last):
  File "/home/azureuser/anaconda3/envs/pc/lib/python3.10/asyncio/selector_events.py", line 159, in _accept_connection
  File "/home/azureuser/anaconda3/envs/pc/lib/python3.10/socket.py", line 293, in accept
OSError: [Errno 24] Too many open files
```
this error happens while production serving, and it is not because specific code but just happing. 
This is probably an error caused by a socket being left open and unclosed somewhere in the backend.

**Comment by DongyoungKim2** [comment]
I narrow down the problem and finally the website get stable.

The main issue was `session` usage with sqlite db. I made all session functions to return something (`return none`, for example)  and minimize session scope. As noted, sqlite is not for production. 

Also, got gold version 0.1.33, which is stable for both backend and frontend. the latest version in current, 0.1.34 has issue with unstable frontend. 

Anyway, thank you for the comment. just fyi, we're currently operating a demo website using pynecone (http://www.kb-gpt.com/) and working fine.
