### ISSUE TITLE
pc run --env prod error in Windows

### ISSUE THREAD

**Issue by evandeng2009** [pynecone-io/pynecone#1244]
**Describe the bug**
pc run in Windows with --env dev is normal, while --env prod has the following error, and building app progress is 40%.

`
File "C:\Users\haha\AppData\Roaming\Python\Python311\site-packages\pynecone\pc.py", line 152, in run
    setup_frontend(Path.cwd(), loglevel)
  File "C:\Users\haha\AppData\Roaming\Python\Python311\site-packages\pynecone\utils\build.py", line 249, in setup_frontend_prod
    export_app(loglevel=loglevel)
  File "C:\Users\haha\AppData\Roaming\Python\Python311\site-packages\pynecone\utils\build.py", line 129, in export_app
    for line in export_process.stdout:
UnicodeDecodeError: 'gbk' codec can't decode byte 0x8c in position 68: illegal multibyte sequence
`

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Pynecone Version: 0.1.34
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by evandeng2009** [comment]
Hi @ElijahAhianyo , it returns cp936.

**Comment by ElijahAhianyo** [comment]
@evandeng2009 can you share your code or a repo that produces this error with me? Im currently not able to reproduce this

**Comment by ozeranskii** [comment]
@evandeng2009 check the startup from the #1250 branch

**Comment by evandeng2009** [comment]
Reproduce this error requires Chinese env I guess, cp936 means GB 2312 char code. Looks like there is some Chinese words. I'll do a debug first. However it's little strange as --env dev is working fine for me in Windows, and --env prod also is ok, with the same code, in Linux.

Right now I'm reinstalling Python and then will have a try.

**Comment by ozeranskii** [comment]
@evandeng2009 @ElijahAhianyo to reproduce the problem it is sufficient to set `encoding="gbk"` as argument `subprocess.Popen`
https://github.com/pynecone-io/pynecone/blob/73895b82b70be6ab82d06c5fc22dd05675faa2a3/reflex/utils/build.py#L118-L125
