### ISSUE TITLE
rx command is not supported in reflex==0.1.34, it only has rf command

### ISSUE THREAD

**Issue by milochen0418** [pynecone-io/pynecone#1263]
**Describe the bug**

`pip install reflex==0.1.34`
There is no file.
`
/Users/milochen/anaconda3/envs/rx/bin/rx
`
But we have the file.
`
/Users/milochen/anaconda3/envs/rx/bin/rf
`

From the old version `pc command`, we expect the `rx` should be the command.  
So the following is the correct file for the command.
`
/Users/milochen/anaconda3/envs/rx/bin/rx
`

**To Reproduce**
```
pip install reflex==0.1.34
```
```
which rx
```

 - Code/Link to Repo:
 - 

**Expected behavior**
After using `which rx`, we should see the result like the following if we use conda the build virtual envrionment
```
/Users/milochen/anaconda3/envs/rx/bin/rx
```
**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.1.34
 - OS:  Mac 
 - Browser (Optional): Chrome
 
**Additional context**

**Comment by ElijahAhianyo** [comment]
yeah, this should be fixed in the next release

**Comment by masenf** [comment]
The current plan is to have the command just be `reflex`, without the shortened alias.

`python -m reflex.reflex` also works, for example when running with a specific interpreter.
