### ISSUE TITLE
ModuleNotFoundError: No module named 'pcconfig' after converting from pynecone to reflex

### ISSUE THREAD

**Issue by masenf** [pynecone-io/pynecone#1269]
**Describe the bug**
When converting a pynecone project that wants to import `pcconfig`, the conversion process renames the module, but does not fix the import.

**To Reproduce**
1. install pynecone
2. pc init
3. install reflex
4. reflex init
5. answer yes to convert the project
6. reflex run

This produces the traceback in the title

**Expected behavior**
Converting pynecone project works without manual intervention.

** Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: `main`
 - OS: macOS 13.4.1
 - Browser (Optional):

**Comment by picklelo** [comment]
Good catch -  maybe we can add this substitution as part of the migration function?

**Comment by masenf** [comment]
@picklelo yep, i'll work on a patch
