### ISSUE TITLE
Replace pkg_resources with importlib

### ISSUE THREAD

**Issue by siddhantgoel** [pynecone-io/pynecone#1300]
**Describe the bug**
At the moment when I run `pytest` it reports the following warning at the end of the test run.

```
=============================== warnings summary ===============================
../../../root/.cache/pypoetry/virtualenvs/geniepy-2RGjdARo-py3.11/lib/python3.11/site-packages/reflex/constants.py:9
  /root/.cache/pypoetry/virtualenvs/geniepy-2RGjdARo-py3.11/lib/python3.11/site-packages/reflex/constants.py:9: DeprecationWarning:
  
  pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================== 27 passed, 1 warning in 1.43s =========================
```

PyPA also has the following "attention" block on its documentation and [recommends](https://setuptools.pypa.io/en/latest/pkg_resources.html) using `importlib` for newer codebase.

<img width="835" alt="Screenshot 2023-07-04 at 7 57 02 PM" src="https://github.com/pynecone-io/pynecone/assets/79892/06d53ae2-7368-4c40-9620-a67cb1674fb4">

**To Reproduce**
- Run pytest on a bare Reflex application

**Expected behavior**
`pkg_resources` is replaced with `importlib`.

**Screenshots**
-

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Reflex Version: 0.2.0
 - OS: macOS
 - Browser (Optional):

**Additional context**
-

**Comment by masenf** [comment]
Thanks for filing this issue. Just wondering if you plan to contribute a fix? Seems like it would be a good entry-level issue.

**Comment by siddhantgoel** [comment]
Sure, I'm happy to submit a PR.
