### ISSUE TITLE
Can't use id-based anchor link in foreach loop

### ISSUE THREAD

**Issue by simonmesmith** [pynecone-io/pynecone#1302]
**Describe the bug**

If you use the `id` field of a component within a `foreach` loop, you get an error. This prevents you from taking advantage of the anchor linking functionality introduced in #469.

**To Reproduce**

* Create a list of objects that have an ID field
* Create a foreach loop with a component within it
* Set the `id` field of the component to the ID of objects in the list
* You will get an error

**Expected behavior**

You should be able to set the `id` on components within a `foreach` loop so you can anchor link to items generated by the loop.

**Specifics:**
 - Python Version: 3.11.4
 - OS: Mac
 - Browser: Chrome
 
**Additional context**

The specifics of my case are:

- I have a references page
- The page is generated dynamically at /references/{entity_one}/{entity_two} to provide references for the relationship between the two entities specified
- I generate the references using a `foreach` loop over a list of `Reference` objects
- I want to anchor link directly to references, using the format /references/{entity_one}/{entity_two}#reference_id
- However, if I add any component within the foreach loop and set its `id` value to reference.reference_id, I get an error (a "hard navigation" type of error specifically)
- My solution was to use the `html` component to create an `<a name="reference.reference_id"></a>` anchor

**Comment by masenf** [comment]
Is this the error that you were getting:

```console
TypeError: expected string or bytes-like object, got 'BaseVar
```

I hacked together this repro script based on your description, but not sure if it's the same problem.

```python
import reflex as rx


class Thing(rx.Model):
    id: int


class State(rx.State):
    n_things: int = 300

    @rx.cached_var
    def stuff(self) -> list[Thing]:
        return [
            Thing(id=x)
            for x in range(self.n_things)
        ]


def index() -> rx.Component:
    return rx.fragment(
        rx.color_mode_button(rx.color_mode_icon(), float="right"),
        rx.link("Go to 69", href="#69"),
        rx.foreach(
            State.stuff,
            lambda t: rx.text("Foo ", t.id, id=t.id),
        ),
    )


app = rx.App(state=State)
app.add_page(index)
app.compile()
```

Anyway, I posted a fix for that issue ☝️assuming it's the same.

**Comment by simonmesmith** [comment]
I haven't tested this, but it looks like it's a good candidate to be the source of the issue. I can post again if I encounter further problems.
