### ISSUE TITLE
Markdown component not working

### ISSUE THREAD

**Issue by matt-grain** [pynecone-io/pynecone#132]
Hi,

I was trying the doc examples for markdown and latex but I don`t have the same result:

````python
def show_equation():
    return pc.vstack(
        pc.markdown("Equation"),
        pc.markdown(
            """
            Support us at **[Pynecone](https://pynecone.io)**.
            Format your `inline_code` easily.
            """
        ),
        pc.markdown(r"\int_a^b x^2 dx $"),
    )
````

![image](https://user-images.githubusercontent.com/111311078/208271277-e3aca65f-1ac1-45a0-affa-4411279dfd8f.png)

Is there something to enable?

OS: Windows 10/WSL/ubuntu
Pynecone: 0.1.10

Thanks!

**Comment by FHU-yezi** [comment]
Try to indent your string block to first level, same to `def`.

We are going to add auto de-indent to fix this problem.

**Comment by matt-grain** [comment]
ah! ok! works now for the block.
What about the latex?

**Comment by matt-grain** [comment]
Ah ok it works with another latex equation: 

````python
        pc.markdown(r"$$V_{sphere} = \\frac{4}{3}\\pi r^3$$"),
````
