### ISSUE TITLE
FastAPI crashes without trace with a substate of a substate

### ISSUE THREAD

**Issue by matt-grain** [pynecone-io/pynecone#140]
I finally understood what causes the problem (but not why). due to the refactoring, I have sub-sub-states and that is the issue:

````python
from typing import List, Dict
import pynecone as pc


class ButtonModel(pc.Model, table=False):

    title: str


class AppState(pc.State):
    """The app state."""

    default_field: str


class LocalState(AppState):

    button_state: List[bool] = [False for i in range(10)]

    @pc.var
    def get_buttonmodel(self) -> List[ButtonModel]:
        self.default_field = "break me"
        return [ButtonModel(id=0, title="this is a button which breaks pynecone"), ButtonModel(id=1, title=self.default_field)]


class SubState(LocalState):
    def trigger_fault(self) -> None:
        print("error")


def index():
    return pc.center(
        pc.vstack(
            pc.foreach(LocalState.get_buttonmodel, lambda a_model: display_form(a_model)),
            spacing="1.5em",
            font_size="2em",
        ),
        padding_top="10%",
    )


def display_form(model: ButtonModel):

    return pc.button(model.title, size="lg", on_click=SubState.trigger_fault)


# Add state and page to the app.
app = pc.App(state=AppState)
app.add_page(index)
app.compile()

````

![image](https://user-images.githubusercontent.com/111311078/208309037-40cdb13d-1b53-40d8-9ae9-b2f71552d452.png)

_Originally posted by @matt-grain in https://github.com/pynecone-io/pynecone/discussions/136#discussioncomment-4442646_

**Comment by picklelo** [comment]
Thanks for the full code, I'll look into what's causing this.

**Comment by picklelo** [comment]
There was an issue for event handlers in sub-substates - I'm putting up a patch for this.

**Comment by matt-grain** [comment]
Great!! Will you make a 0.1.11a release? :D I'd love to test it!

**Comment by picklelo** [comment]
Yep, will have this out today!

**Comment by matt-grain** [comment]
In fact I build the current codebase but my app looked broken, looks like the websocket stuff was buggy. So I’ll wait for the next release :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
