### ISSUE TITLE
Tailwind support

### ISSUE THREAD

**Issue by Wazarr94** [pynecone-io/pynecone#141]
Would it be possible to add Tailwind in the base project? It's a very popular framework for styling and it is compatible with chakra: https://github.com/chakra-ui/chakra-ui/issues/634

Here's a quick example on how it could be used:

```py
def index():
    return pc.center(
        pc.vstack(
            pc.heading("Hello world!", class_name="text-xl"),
        ),
        class_name="pt-8",
    )
```

**Comment by FHU-yezi** [comment]
Yes I have known this and it is awesome, maybe we can add this as a optional dependence?

And Plotly.js should also be optional, at not it seems that we included Plotly.js in our backend assets, whatever it is be used or not.

**Comment by picklelo** [comment]
Yes, we can look into this. We need to add support for stylesheets and class names in the components, but should be possible.

**Comment by Fire-Hound** [comment]
Hey everyone, is this still in active development?

**Comment by kbrgl** [comment]
We now have provisional support for Tailwind in Pynecone through raw HTML elements (https://github.com/pynecone-io/pynecone/pull/627).

**Comment by kbrgl** [comment]
We now provide Tailwind support through #1155.
