### ISSUE TITLE
Add Integration Tests on Merge to Main

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#151]
Add integration test so that after a pr is a approved on the merge to main it will do the following.

1.  Clone pynecone-website repo
2.  pc init 
    - Check the bun install
    - Check the project directory structure (.web, assets, pcconfig.py)
4.  pc run 
    - Make sure it can run without errors

**Comment by FHU-yezi** [comment]
After this PR is merged, can we contribute to Pynecone's website via the website repo?

**Comment by Alek99** [comment]
> After this PR is merged, can we contribute to Pynecone's website via the website repo?
Hi yes you will be able to add suggestions and contribute to the website

**Comment by Alek99** [comment]
Sorry for all the spam on the commits to the pr this seems to be the only way to easily debug GitHub actions

**Comment by FHU-yezi** [comment]
You means we should push it to remote and we can see the result?

See this, run GitHub Action locally: https://github.com/nektos/act

**Comment by Alek99** [comment]
Nice thanks Ill check it out
