### ISSUE TITLE
Add option to specify port

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#157]
Either in the `pcconfig` or as a flag to `pc run` we should be able to set the port on which we run the app.

**Comment by Alek99** [comment]
Both would be nice I see the config being useful for repeat runs but flag would be nice for sh scripts

**Comment by FHU-yezi** [comment]
And throw an error if this port is already in use, our default behavior now is to find another port avaliable.

**Comment by pysqz** [comment]
please see this pr [#192](https://github.com/pynecone-io/pynecone/pull/192)
