### ISSUE TITLE
Missing `set_color()` in `ColorPickerState()` in [https://pynecone.io/docs/advanced-guide/wrapping-react](url)

### ISSUE THREAD

**Issue by forhonourlx** [pynecone-io/pynecone#196]
**Describe the bug**
A missing function in [https://pynecone.io/docs/advanced-guide/wrapping-react](url)

**To Reproduce**
Missing `set_color()` in `ColorPickerState()`
```
def set_color(self, color):
        self.color = color
```
in
```
class ColorPickerState(pc.State):
    color: str = "#db114b"

def index():
    return pc.box(
        pc.vstack(
            pc.heading(ColorPickerState.color),
            color_picker(
                on_change=ColorPickerState.set_color
            ),
        ),
        background_color=ColorPickerState.color,
        padding="5em",
        border_radius="1em",
    )
```

** Specifics (please complete the following information):**
 - Python Version:3.9
 - Pynecone Version:0.1.11
 - OS: WSL2
 - Browser (Optional):Chrome

**Comment by Alek99** [comment]
This is actually automatically set by Pynecone if you use set_color or set_any_state_var the framework will automatically set that variable for you. It is more of a short had but behind the scenes it would be equivalent to this 


``` python
def set_color(self.color)
      self.color = color
```

I can make this more clear in the docs.

**Comment by forhonourlx** [comment]
Got the feature, a shortcut of `def set_xxx()`. Thank you.
