### ISSUE TITLE
Uppercase event handlers don't work

### ISSUE THREAD

**Issue by DPetuskey** [pynecone-io/pynecone#197]
**Describe the bug**
State does not update when there are uppercase functions in State.

**Expected behavior**
Expected my event handler DFS to properly update State but does not update unless I use a lower case title "dfs"

**Screenshots**
<img width="1440" alt="Screen Shot 2022-12-31 at 12 39 01 AM" src="https://user-images.githubusercontent.com/98362056/210130717-4d76b165-46f8-4fe9-8371-f682bded63c4.png">

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 1.10
 - OS: 
 - Browser (Optional):

**Comment by Alek99** [comment]
This is probably something with our snake_case handling I suspect

**Comment by Alek99** [comment]
Works in this upcoming release v0.1.14
