### ISSUE TITLE
Nested pc.foreach doesn't work as expected

### ISSUE THREAD

**Issue by DPetuskey** [pynecone-io/pynecone#198]
**Describe the bug**
Tried to implement nested foreach while dealing with a 2D array and it did not work. Trying to index into a 2D list doesn't update the grid properly. 

**Expected behavior**
Expected a grid to be produced with nesting for a 2D array. 

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 1.10
 - OS: 
 - Browser (Optional):

**Comment by picklelo** [comment]
@DPetuskey I think the rendering issue might be related[ to this](https://stackoverflow.com/questions/47402365/how-to-have-nested-loops-with-map-in-jsx), you may need to wrap the second `foreach` in an other element for it to render - i.e. you can't directly have a `foreach` in a `foreach`. We should update the docs here.

I was able to get this code to work correctly:
```
import pynecone as pc

class State(pc.State):
    """The app state."""

    array2d: list[list[int]] = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


def index():
    """The main view."""
    return pc.vstack(
        pc.foreach(
            State.array2d,
            lambda x: pc.hstack(pc.foreach(
                x,
                pc.text
            ))
        ),
    )


# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index, title="Foreach Example")
app.compile()
```

Lmk if that fixes your issue.
