### ISSUE TITLE
`Avatar` shows '\', is there escape character support issue?

### ISSUE THREAD

**Issue by forhonourlx** [pynecone-io/pynecone#204]
**Describe the bug**
I am trying to create an `Avatar` with prop `name` of “登录”, which is a non-English string. `Avatar` shows `\`(support issues of utf-8 escape character)?
And is there any way to control the display length on `Avatar`?
Thanks inadvance.

**To Reproduce**
```
                pc.menu_button(
                    pc.cond(
                        cond = GlobeState.logged_in,
                        comp1 = pc.avatar(name=GlobeState.username,size="md"),
                        comp2 = pc.avatar(size="md", name="登录"),
                    )
                ),
```

**Screenshots**

![Avatar](https://user-images.githubusercontent.com/16576219/210628000-f90cfb6a-ab14-4c5d-b5a5-a7184d4ae708.png)

** Specifics (please complete the following information):**
 - Python Version: 3.10
 - Pynecone Version: 0.1.11
 - OS: WSL2
 - Browser (Optional): EDGE

**Comment by Alek99** [comment]
I think this should be fixed now. Reopen if not, thanks.
