### ISSUE TITLE
Add Docs for New Features

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#208]
Features to add documentation for:
- LogLevel
- Nested foreach

**Comment by picklelo** [comment]
Some other things:
* `pc.foreach` where the render method has access to the loop index. e.g.
```
pc.foreach(State.items, lambda item, index: pc.text(index))
```
* Improved substate docs. We can have more thorough and motivated examples that reflect real world use cases. For example, creating a substate for each page.
