### ISSUE TITLE
How to create a sider nav bar with great mobile adaption? like official site[https://pynecone.io/docs/getting-started/introduction](url)

### ISSUE THREAD

**Issue by forhonourlx** [pynecone-io/pynecone#209]
**Describe the bug**
Hi Pynecone Team,
How to create a sider nav bar like official site[https://pynecone.io/docs/getting-started/introduction](url)
Whatsmore, it shows good mobile adaption. Is that feature framework inherent? Or more codes should taken?
Could you kindly share an example of nice nav bar? That would be of great help to users.
Thanks indavance.
![f49a828c65e75898e8ec504719e513d](https://user-images.githubusercontent.com/16576219/210705551-9469cb1d-901e-46df-8cdd-f2528829a8ee.jpg)

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.10
 - Pynecone Version: 0.1.11
 - OS: WSL2
 - Browser (Optional): Andriod Chrome

**Comment by Alek99** [comment]
Its inherent, you can find that exact nabber [here](https://github.com/pynecone-io/pcweb/blob/main/pcweb/components/navbar.py) we have Open-sourced our whole landing pange/docs

**Comment by forhonourlx** [comment]
Thanks @Alek99 
You just gave the very key instruction, I will try.
