### ISSUE TITLE
Global style is not working

### ISSUE THREAD

**Issue by Lendemor** [pynecone-io/pynecone#216]
**Describe the bug**
According to the doc at https://pynecone.io/docs/styling/overview, we can use global styling, however, using the `style` parameter in `pc.App()` has no impact on the display.

**To Reproduce**
Snippet to reproduce the behavior:
```
test_style = {"font_size": 54}
def index():
    return pc.text("My title")
app = pc.App(state=MyState, style=test_style)
app.add_page(index, path="")
app.compile
```
**Observed behavior**
![image](https://user-images.githubusercontent.com/4015177/210905419-197008e8-7ad9-42a0-9e84-7041d244ee08.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/4015177/210905515-6948d3df-fa11-448f-b916-032647643bfd.png)
(generated this result by passing `test_style` directly to `pc.text()`

** Specifics (please complete the following information):**
 - Python Version: 3.10.6
 - Pynecone Version: 0.1.11
 - OS: Ubuntu 22.04
 - Browser (Optional): Chrome/VS Browser

**Comment by picklelo** [comment]
We will improve the docs here, but behind we are using [Chakra global styles](https://chakra-ui.com/docs/styled-system/global-styles) and it looks like you need to specify the `body` tag if you want to get the text styles.

Try this out as your style dict:
```
test_style = {"body": {"font_size": "54"}}
```

**Comment by Lendemor** [comment]
Got it.
Although I want to ask, to keep things consistent with the other kind of styling, wouldn't it be better if the App() did this internally:

`style = {"body": style}`

Or maybe there are some reason it can't work like that.
(I used font_size as an example, though it's not necessarily the only CSS I want to set globally).

I'll wait for the updated doc and see if it clear thing up for me.
