### ISSUE TITLE
Improve doc page about styling

### ISSUE THREAD

**Issue by Lendemor** [pynecone-io/pynecone#219]
Earlier today I was trying to set my CSS to do something basic, aka defining a color for `hover` on one component.

However, the doc page about styling doesn't reference how to do that specifically.

At first glance, the only thing slightly different in the example is `"::selection"` (not sure what this does by the way, I tried it but didn't see any effect).

So I tried `"::hover"` which obviously didn't work. After a while spent trying different things and wondering if I messed up somewhere, I stumbled on the Chakra docs which DOES have that information (what I needed was `"_hover"`) but it's not very intuitive, because I add to click the `see full list of prop` link to get there and then click `Chakra Factory`, which isn't exactly what I was looking for.

So I think there is definitely an improvement possible for the docs on this point, either : 
- by adding more informations directly in your own docs
- by making it easier to find things in the chakra docs (more links?) if you don't feel like repeating it.

Cheers.

**Comment by Alek99** [comment]
Sounds good we are currently adding a search feature to the docs aswell should have this done in the next few days. I'll add more styling docs aswell when we deploy

**Comment by picklelo** [comment]
Added in the "Special Styles" section: https://pynecone.io/docs/styling/overview
