### ISSUE TITLE
DataTable: nested components

### ISSUE THREAD

**Issue by jerguslejko** [pynecone-io/pynecone#220]
**Describe the ~bug~feature request**
When using `pc.data_table` component, I would like to display a list of items and for each row, I want to add a button/action to perform on that row. Eg. I have a list of posts, and would like to have a `publish/unpublish` button on each row.

**Expected behavior**

Something like this would work:

```py
            pc.data_table(
                data=[
                    ["Post 1", pc.button('publish')],
                    ["Post 2", pc.button('unpublish')],
                ],
                columns=["Post name", "Actions"],
            ),
```

Currently, this fails with `TypeError: Object of type Button is not JSON serializable`

**Comment by Alek99** [comment]
Currently datatable can't take in any components inside of it. This may be possible to do I'll look into it. In the meantime id use the table component in combination with foreach to render each row for your use case.

Something like this :

``` python

"""Welcome to Pynecone! This file create a counter app."""
import pynecone as pc
from typing import List


class State(pc.State):
    data: List[List[str]] = [["Post 1", "publish"], ["Post 2", "unpublish"], ["Post 3", "publish"]]


def render_row(row):
  return pc.tr(
      pc.td(row[0]),
      pc.cond(
        row[1] == "publish",
        pc.td(pc.button("Publish")),
        pc.td(pc.button("unpublish")),
      )
  )



def index():
  return pc.table(
    pc.thead(
        pc.tr(
            pc.th("Name"),
            pc.th("Status"),
        )
    ),
    pc.tbody(
        pc.foreach(
          State.data,
          render_row,
        )
    )
)
# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index, title="TableExample")
app.compile() 
```

Hopefully well be able to include this feature in the future need to look into gridjs capabilities because that's what we compile down to for datable

**Comment by jerguslejko** [comment]
@Alek99 that works, thank you! having it in datatable would be even better, but this is also nice 👍

**Comment by FHU-yezi** [comment]
For this example, how can we know which button is clicked in callback function? Maybe we should use a lambda function and pass a unique id to each callback func.
