### ISSUE TITLE
Difficulty with accessing value from State

### ISSUE THREAD

**Issue by Lendemor** [pynecone-io/pynecone#221]
**Describe the bug**
This might not be a bug, and rather the intended way for things to work, but I wanted to access some data fom a dict inside my State, and I can't get the value.

**To Reproduce**
Minimal snippet to reproduce the behavior:
```
from icecream import ic
import pynecone as pc

class UIState(pc.State):
    """The app state."""

    my_dict = {"A": "one_value", "B": "another_value"}


def index():
    txt = "A"
    try:
        link = UIState.my_dict.get(txt)
    except Exception as e:
        ic(e)
    try:
        link = UIState.my_dict[txt]
        ic(link, str(link))
        return pc.link(txt, href=link)
    except Exception as e:
        ic(e)

    exit(1)
```

**Expected behavior**
Obtaining the value of type `str` from my dict.

**Screenshots**
Output of running the above snippet:
![image](https://user-images.githubusercontent.com/4015177/211151256-73b9ac35-464c-47d0-9e6a-96234d946414.png)

** Specifics (please complete the following information):**
 - Python Version: 3.10.6
 - Pynecone Version: 0.1.11
 - OS: Ubuntu 22.04
 
**Additional context**
Wanted to centralize some information inside State to make my code cleaner, and ran into that problem.

**Comment by Lendemor** [comment]
Yet another example where things don't work how I'd expect them to.
I have this in my State:
```
authenticated: bool = False
```
and this code to generate an icon :

```
def auth_icon():
    ic(NavState.authenticated)
    if NavState.authenticated:
        tag = "LockIcon"
        method = NavState.logOut
    else:
        tag = "UnlockIcon"
        method = NavState.openUnlockModal
    return pc.menu_item(
        pc.icon(tag=tag),
        unlock_modal(),
        on_click=method,
    )
```
I'd expect the icon to change depending on the value in `authenticated`, expect it always evaluate to True because the value look like that : 
```
ic| NavState.authenticated: BaseVar(name='authenticated', type_=<class 'bool'>, state='state', is_local=False, is_string=False)
```

How am I supposed to access the value of `authenticated`, rather than the BaseVar object?

**Comment by Alek99** [comment]
Ok looking now

**Comment by Alek99** [comment]
For the auth_icon you need to use pc.cond if you want to do conditional rendering based on state var see here https://pynecone.io/docs/library/layout/cond

**Comment by Alek99** [comment]
I think the confusion may be this. In your UI function index you cannot set `link = UIState.my_dict[txt]`. Any state references should only be used in pc components. Let me know if this makes sense

**Comment by Alek99** [comment]
But there actually may be a separate error having a state var as href. I think well need to fix something for this

**Comment by Lendemor** [comment]
> For the auth_icon you need to use pc.cond 

I will try that, but my first impression on that solution is that it will work because I only have 2 icon to render.
If I had, let's say, to render conditionally between 5 different states, would I have to stack conds to match each possible case? (i.e I would need 5 pc.cond components and 4 "computed?" boolean to display them)
It make thing complicated for no benefit imo, so there might be improvement possible on that side?

> Any state references should only be used in pc components.

The Docs actually mentions "Base Vars: Can only be modified within event handlers." but never said a thing about the scope limit for reading them. Thanks for clarifying that one.

---

Back to the cond component, I did try it, but I'm now stuck with : 
```
def auth_check(self):
    ic(self.authenticated)
    if self.authenticated:
        self.log_out()
    else:
        self.open_unlock_modal()
```
when I enter `auth_check`, the var is `False` so I enter the `else`, but `open_unlock_modal()` is never called.
```
ic| self.authenticated: False
```

Is there another implicit "You can't call a state method (aka event handler) from another event handler?" that is missing from the documentation?
If so, I think it's really limiting because I'll have to either : 
- do all the logic for a specific event inside that method (work if there isn't much to do, can be annoying for more complex method, and also not very good for DRY)
- define external method which can actually be called? (by passing the state `self` to  a method defined outside the State, I can actually modify `obj.authenticated` value [because parent method is an event handler I guess], however, `pc.cond` seems to ignore it as it doesn't change which icon is displayed)

**Comment by Lendemor** [comment]
#225 was a problem on my side.

Now I have the correct behavior for the events, but the `pc.cond()` always display the `False` option, regardless of the actual value in State.authenticated. 

My code :
```
def auth_icon_():
    return pc.menu_item(
        pc.cond(
            NavState.authenticated,
            pc.icon(tag="LockIcon"),
            pc.icon(tag="UnlockIcon"),
        ),
        on_click=NavState.auth_check,
    )
```
I also tried the above without menu_item in case something interfere, but result is the same in either case, the icon does not change.

**Comment by Alek99** [comment]
> #225 was a problem on my side.
> 
> Now I have the correct behavior for the events, but the `pc.cond()` always display the `False` option, regardless of the actual value in State.authenticated.
> 
> My code :
> 
> ```
> def auth_icon_():
>     return pc.menu_item(
>         pc.cond(
>             NavState.authenticated,
>             pc.icon(tag="LockIcon"),
>             pc.icon(tag="UnlockIcon"),
>         ),
>         on_click=NavState.auth_check,
>     )
> ```
> 
> I also tried the above without menu_item in case something interfere, but result is the same in either case, the icon does not change.

Ok this may be a bug ill test it today

**Comment by Lendemor** [comment]
Bug with the icon doesn't occurs anymore as of v0.1.12.

**Comment by gschurck** [comment]
@Lendemor concerning the issue to access dict values by keys values in states, I found a workaround after some investigation.

As it seems that pynecone want to know the type of elements in dict, I tried to define a TypedDict, but it didn't work.
I finally ended trying to define a pydantic BaseModel to define the types, and convert dict to corresponding models. And it worked !
After checking the pynecone code, I just found that there is the class pc.Base already herited from pydantic BaseModel, so you should use that.

```py
class TrainClass(pc.Base):
    id: int
    seat_class: str
    available_seats_count: int
    price_flexible: float
    price_not_flexible: float

class Train(pc.Base):
    id: int
    departure_station: str
    arrival_station: str
    departure_date: str
    departure_time: str
    classes: List[TrainClass] = []
```

And then you can access object attributes when rendering your components, and even access nested types.
Like `train.classes[0].available_seats_count`.
