### ISSUE TITLE
Link State Var Href JS Error

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#224]
**Describe the bug**
It seems href is not working with a state var. Getting a JS error in browser.

```
Error: Multiple children were passed to <Link> with `href` of `one_value` but only one child is supported https://nextjs.org/docs/messages/link-multiple-children
```
**To Reproduce**
 - Code/Link to Repo:

```python
"""Welcome to Pynecone! This file create a counter app."""
import pynecone as pc
from typing import Dict

class State(pc.State):
    my_dict: Dict[str, str] = {"A": "/onevalue", "B": "/anothervalue"}

def index():
  return pc.link(
    pc.text("A"),
    href=State.my_dict["A"]
  )
# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index, title="TableExample")
app.compile() 
```
**Expected behavior**
 Expect it to work as a regular state var reference.
** Specifics (please complete the following information):**
 - Python Version:3.11
 - Pynecone Version:0.1.11
 - OS: Mac

**Comment by picklelo** [comment]
I think you can't pass a `pc.text` (or any other component) to a `pc.link`. This should work:
```
def index():
  return pc.link(
    "A",
    href=State.my_dict["A"]
  )
```

We should throw an exception in the compiler to catch this to avoid any JS errors.

**Comment by xugaoxiang** [comment]
Same error on v0.1.11，python 3.8, nodejs 18.12.1, windows 10 64bit

I use pc init and then pc run， powershell console outputs

`
> dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
event - compiled client and server successfully in 12.6s (761 modules)
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

wait  - compiling / (client and server)...
event - compiled client and server successfully in 1596 ms (830 modules)
wait  - compiling /_error (client and server)...
error - node_modules\next\dist\client\link.js (216:22) @ Object.LinkComponent [as render]
error - Error: Multiple children were passed to <Link> with `href` of `https://pynecone.io/docs/getting-started/introduction` but only one child is supported https://nextjs.org/docs/messages/link-multiple-children
    at Object.LinkComponent [as render] (webpack-internal:///./node_modules/next/dist/client/link.js:216:23)
    at ReactDOMServerRenderer.render (C:\Users\Administrator\Desktop\pc_app\.web\node_modules\react-dom\cjs\react-dom-server.node.development.js:3872:44)
    at ReactDOMServerRenderer.read (C:\Users\Administrator\Desktop\pc_app\.web\node_modules\react-dom\cjs\react-dom-server.node.development.js:3690:29)
    at Object.renderToString (C:\Users\Administrator\Desktop\pc_app\.web\node_modules\react-dom\cjs\react-dom-server.node.development.js:4298:27)
    at renderDocument (C:\Users\Administrator\Desktop\pc_app\.web\node_modules\next\dist\server\render.js:736:47)
    at Object.renderToHTML (C:\Users\Administrator\Desktop\pc_app\.web\node_modules\next\dist\server\render.js:819:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async doRender (C:\Users\Administrator\Desktop\pc_app\.web\node_modules\next\dist\server\base-server.js:687:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (C:\Users\Administrator\Desktop\pc_app\.web\node_modules\next\dist\server\base-server.js:796:28)
    at async C:\Users\Administrator\Desktop\pc_app\.web\node_modules\next\dist\server\response-cache\index.js:80:36 {
  page: '/'
}
`

**Comment by Alek99** [comment]
Can you send a snippet of your code or is it the code from above?

**Comment by Alek99** [comment]
Ah ok I see your on windows we almost have windows support done should have it up soon this is the last error to fix

**Comment by xugaoxiang** [comment]
> Can you send a snippet of your code or is it the code from above?

source code 

`
"""Welcome to Pynecone! This file outlines the steps to create a basic app."""
from pcconfig import config

import pynecone as pc

docs_url = "https://pynecone.io/docs/getting-started/introduction"
filename = f"{config.app_name}/{config.app_name}.py"


class State(pc.State):
    """The app state."""

    pass


def index():
    return pc.center(
        pc.vstack(
            pc.heading("Welcome to Pynecone!", font_size="2em"),
            pc.box("Get started by editing ", pc.code(filename, font_size="1em")),
            pc.link(
                "Check out our docs!",
                href=docs_url,
                border="0.1em solid",
                padding="0.5em",
                border_radius="0.5em",
                _hover={
                    "color": "rgb(107,99,246)",
                },
            ),
            spacing="1.5em",
            font_size="2em",
        ),
        padding_top="10%",
    )


# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index)
app.compile()

`

**Comment by Alek99** [comment]
Working on this now

**Comment by Inkee1** [comment]
Same issue. """Error: Multiple children were passed to <Link> with `href` of [`https://pynecone.io/docs/getting-started/introduction`](http://127.0.0.1:8999/%60https://pynecone.io/docs/getting-started/introduction%60) but only one child is supported https://nextjs.org/docs/messages/link-multiple-children""   I installed pynecone today

**Comment by xugaoxiang** [comment]
> Working on this now

Error still exists, already update to v0.1.12.
