### ISSUE TITLE
Event handler can not call another event handler

### ISSUE THREAD

**Issue by Lendemor** [pynecone-io/pynecone#225]
**Describe the bug**
In a given `State`, if I have 2 event handler (i.e. `func1` and `func2`) and `func1` is the one being linked to an event, it does not call `func2` even if code say otherwise. 

**To Reproduce**
Snippet to reproduce the behavior:
```
from icecream import ic
import pynecone as pc


def out_func(obj):
    ic()


class UIState(pc.State):
    def func1(self, a):
        ic()
        self.func2()
        out_func(self)

    def func2(self):
        ic()


def index():
    return pc.center(pc.input(on_change=UIState.func1))


# Add state and page to the app.
app = pc.App(state=UIState)
app.add_page(index)
app.compile() 
```

**Expected behavior**
I expect `func2` to be called, or to have a way to define non-event method inside a `State` so I don't have to write States method outside of my State object.

**Screenshots**
Output of above snippet:
![image](https://user-images.githubusercontent.com/4015177/211199543-44726965-4c25-43b9-8789-beada0db560b.png)

** Specifics (please complete the following information):**
 - Python Version: 3.10.6
 - Pynecone Version: 0.1.11
 - OS: Ubuntu 22.04
 
**Additional context**
(made a separate issue for a problem that showed up in issue #221 )

**Comment by Alek99** [comment]
You'll need to return it, checkout out our docs under Triggering Events From Event Handlers. https://pynecone.io/docs/state/events

**Comment by Lendemor** [comment]
First option did what I needed, thanks!

(and my bad for now checking more deeply the docs)

**Comment by Alek99** [comment]
No problem happy to answer any questions thanks for trying pynecone out!
