### ISSUE TITLE
Substate documentation unclear

### ISSUE THREAD

**Issue by MikeEgan1** [pynecone-io/pynecone#230]
**Describe the bug**
I am sorry if this is the wrong place for it, but I joined the discord and it seemed empty. When looking through the documentation on substates, it looks very unclear how to include these into the app. 

Since `app = pc.App(state=State)` creates the app, I am unsure how to add one of the substate of this, specifically for another page. In the substates documentation, it does not show how to apply additional states to the app. 

** Specifics (please complete the following information):**
 - Python Version: 3.10
 - Pynecone Version: 0.1.11
 - OS: WSL
 

I will acknowledge this is not a bug, but I did not see another avenue to contact the team and ask for support, as well as, point out the lack of clarity in the documentation. 

With that said, I love pynecone and plan to continue to use it as it grows.

**Comment by MikeEgan1** [comment]
I will close this as I was able to figure it out, any states that inherit from the base start seem to be also included.

**Comment by picklelo** [comment]
Glad you were able to figure it out! Yeah we just made the Discord today... will work on getting it active 😃
