### ISSUE TITLE
Add File Upload Component (pc.upload)

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#238]
Another good first issue but this would be a harder than the [date picker](https://github.com/pynecone-io/pynecone/issues/237) but if someone is up for the challenge this would be a huge help. This component with allow the user to upload a file to the server.

We can investigate if chakra input has this functionality using type="file". Otherwise we can make it from scratch or use another react lib to wrap.

Some requirements would be:
- Can upload multiple types of files: images, json, txt, video...
- User can specify path where the file is stored on the backend

See [here](https://pynecone.io/docs/advanced-guide/wrapping-react) for an intro into wrapping a react component in pynecone.

**Comment by Alek99** [comment]
A good library may be `react-drag-drop-files`.

**Comment by flozi00** [comment]
Would love to help, but have no experience with react.
Came up to this framework after checking huggingface spaces.
File upload would be one of the most useful features for AI applications.
This lib seems interesting because gradio is good for demos, but this could be for products
