### ISSUE TITLE
Create pc.password component

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#256]
This can just be a shorthand for 
```
pc.input(type_="password")
```

but we can also have nice features like automatically hashing the value before storing it in the state, so we never store raw passwords.

**Comment by Imnaseli** [comment]
Hey, good evening I was wondering if I could attempt to add this feature, I could use the argon2 algorithm for the hashing.

**Comment by picklelo** [comment]
@Imnaseli yes that would be great! Feel free to join our Discord too if you need any guidance
