### ISSUE TITLE
Allow Script Tags

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#266]
Sometimes the user may need to provide JS scripts (for example, adding a Google Analytics script to their site). We need a clean way to allow this.

**Comment by gringrape** [comment]
Could I work on this? If so, could you tell me where to start?

**Comment by TommyDew42** [comment]
@gringrape i guess add one more component `ScriptTag` to the codebase. Then we can render that component to the page. So the whole feature would be sth like this?:
```py
script_tag = ScriptTag(url='....')

app = pc.App()
app.add_page(index, scripts=[script_tag])
```

What's @Alek99 idea

**Comment by TommyDew42** [comment]
Is @gringrape still working on this? If no, i can help with that

**Comment by gringrape** [comment]
> Is @gringrape still working on this? If no, i can help with that.
> 
> There's a [discussion](https://discord.com/channels/1029853095527727165/1061493979889278986/1069143840793042984) on discord about how we should implement the `Script` tag.

Thank you! I will check on discord :)

**Comment by ngmisl** [comment]
Just for reference, I have a self-hosted umami script waiting to be implemented

`'<script async defer data-website-id="3c907df2-dc16" src="https://xx.vercel.app/umami.js"></script>'`

Ideally there would be something like pc.script where you could either copy&paste the whole external or define embeds?

**Comment by Shahin-rmz** [comment]
watching this to be implemented.

**Comment by wassafshahzad** [comment]
Can I pick this issue up ?

**Comment by picklelo** [comment]
@wassafshahzad Yes definitely! If you need help/guidance you can post on our Discord for faster replies.

**Comment by wassafshahzad** [comment]
Sure
