### ISSUE TITLE
[get started] Error - Multiple children were passed to <Link>

### ISSUE THREAD

**Issue by cs2jang** [pynecone-io/pynecone#267]
**Describe the bug**
> pc run
....
> dev
> next dev

error - node_modules\next\dist\client\link.js (216:22) @ Object.LinkComponent [as render]
error - Error: Multiple children were passed to <Link> with `href` of `https://pynecone.io/docs/getting-started/introduction` but only one child is supported https://nextjs.org/docs/messages/link-multiple-children
    at Object.LinkComponent [as render] (webpack-internal:///./node_modules/next/dist/client/link.js:216:23)

[Solved]

1. find index.js file (go to .web folder --> pages folder)

2. add `<dev></dev>` tag into `<Link>(here)</Link>`
3.
![image](https://user-images.githubusercontent.com/43163358/212693533-6be8b844-b015-4f20-9717-0bd601c06fa2.png)

![image](https://user-images.githubusercontent.com/43163358/212693638-65b8cad9-57de-4606-aada-455329a1596a.png)

4. rerun

** Specifics (please complete the following information):**
 - Python Version: Python 3.7.7
 - Pynecone Version: pynecone-io 0.1.12
 - OS: Windows 10

**Comment by FHU-yezi** [comment]
Please downgrade to v0.1.11 and tell us if this issue still exist. Maybe one of our new features caused this problem.

**Comment by Alek99** [comment]
We still are working on windows support that seems to be the issue here
