### ISSUE TITLE
How to make a single app with multiple pages to have an individual state for each page?

### ISSUE THREAD

**Issue by YeonwooSung** [pynecone-io/pynecone#268]
Hi,

I am currently trying to build a simple test web with Pynecone.
What I want to add multiple pages to the app, where each page has it's own State for event handling.
However, it seems like pc.App object only accepts one state object as a parameter..
Is this currently not supported? or am I missing something?

Thanks for your help :)

**Comment by FHU-yezi** [comment]
Maybe you can subclass the root state and use substate to access both local and global vars?

I mean you can store global state such as dark mode state in root state obj, and use substate to handle app's logic.
