### ISSUE TITLE
PD.DataFrame is not supported for State

### ISSUE THREAD

**Issue by qu3vipon** [pynecone-io/pynecone#279]
**Describe the bug**
`pd.DataFrame` type is not supported for State

**To Reproduce**
 ```python
class State(pc.State):
    data: pd.DataFrame
```

**Error Message**
```bash
$ TypeError: State vars must be primitive Python types, Plotly figures, Pandas dataframes, or subclasses of pc.Base. Found var “data” with type <class ‘pandas.core.frame.DataFrame’>.
```

**Code**
- couldn’t find `pd.DataFrame` in Valid state var types
```python
# pynecone/utils.py L60

# Valid state var types
PrimitiveType = Union[int, float, bool, str, list, dict, tuple]
StateVar = Union[PrimitiveType, Base, None]
```

**Specifics (please complete the following information):**
 - Python Version: 3.8.10
 - Pynecone Version: 0.1.12
 - OS: mac OS

**Comment by Alek99** [comment]
Looking into this now

**Comment by Alek99** [comment]
This is a bug on our side will be fixing asap

**Comment by Alek99** [comment]
In the mean time it seem computed vars for pandas is working see this example, https://github.com/pynecone-io/pynecone-examples/blob/main/nba/nba/nba.py

**Comment by wongni** [comment]
> In the mean time it seems computed vars for pandas is working see this example, https://github.com/pynecone-io/pynecone-examples/blob/main/nba/nba/nba.py

@Alek99 When I used the computed var in the data_table's `data` prop I am getting this error. Is this also a bug?

```
            pc.data_table(
                data=State.df,
                pagination=True,
                search=True,
                sort=True,
                resizable=True,
            ),
```

<img width="379" alt="image" src="https://user-images.githubusercontent.com/11528277/213936328-257cd8c3-15a0-4797-8cc3-69ae1797f560.png">

**Comment by Alek99** [comment]
Hmm just ran the example and it seems to be working for me what pynecone version are you on and did you change the code at all

**Comment by wongni** [comment]
> Hmm just ran the example and it seems to be working for me what pynecone version are you on and did you change the code at all

I am using pynecone 0.1.13 version and python 3.9.13 version. And the only code I changed in the `nba` example's `main` branch was from `data=nba_data,` to `data=State.df,`.  I tried both Firefox and Chrome browsers on Mac but still got `An error happened while fetching the data` error on the table.

**Comment by picklelo** [comment]
@wongni I'm seeing this too - working on a fix now.
