### ISSUE TITLE
Fix Datatable API

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#28]
Have oneway to support data frames and list.

**Comment by Pranav25191** [comment]
Hi, I would like pick this issue up. could you guide me?

**Comment by Alek99** [comment]
Hi Pranav thank you so much for wanting to contribute! How have you found the project so far?

Right now we decided to only have this component take in a pandas dataframe via the data prop see[ these docs](https://pynecone.io/docs/library/datadisplay/datatable) for an example. I have updated the issue to reflect what we also would want.

The file you would want to modify for this change would be [datatable.py](https://github.com/pynecone-io/pynecone/blob/1d22571829b089d2b7adc2091f89b3d7ecd32476/pynecone/components/datadisplay/datatable.py#L17-L57) specifically in the render method. This one is a little complicated for a first issue but if you up for the challenge feel free to take it on. 

I am going to make a better guide tomorrow on how to run Pynecone locally so you can start contributing to this issue. After I do this I can give some better guidance on how to start tackling this problem.

**Comment by Alek99** [comment]
> Hi Pranav thank you so much for wanting to contribute! How have you found the project so far?
> 
> Right now we decided to only have this component take in a pandas dataframe via the data prop see[ these docs](https://pynecone.io/docs/library/datadisplay/datatable) for an example. I have updated the issue to reflect what we also would want.
> 
> The file you would want to modify for this change would be [datatable.py](https://github.com/pynecone-io/pynecone/blob/1d22571829b089d2b7adc2091f89b3d7ecd32476/pynecone/components/datadisplay/datatable.py#L17-L57) specifically in the render method. This one is a little complicated for a first issue but if you up for the challenge feel free to take it on.
> 
> I am going to make a better guide tomorrow on how to run Pynecone locally so you can start contributing to this issue. After I do this I can give some better guidance on how to start tackling this problem.

Added Issue for Contributing Guide [Here](https://github.com/pynecone-io/pynecone/issues/44)

**Comment by Pranav25191** [comment]
Hi @Alek99, Is this Issue solved?

**Comment by Alek99** [comment]
Hi Pranav yes I solved this issue because its had a weird solution and would be a little difficult for a first issue. 

Can you create a Pynecone app and start testing the framework. This will give you a good understanding of the framework so you can start to contribute in the future.

 I'll try and label some issues as `good first issues` for you future to pick up.

**Comment by Pranav25191** [comment]
Okay thanks, Alek I will do it and pick up another issue. What about the discord server?

**Comment by Alek99** [comment]
Sounds good! We are still waiting to see if people want a discord or not see here https://github.com/pynecone-io/pynecone/discussions/57
