### ISSUE TITLE
Is there any way to empty the input after submission?

### ISSUE THREAD

**Issue by asleep-henry** [pynecone-io/pynecone#281]
**Question**
Can I empty the input after submission? Stale text remains in the input form after submission.

**Comment by FHU-yezi** [comment]
Change state which binded to the value in submit callback?

**Comment by picklelo** [comment]
Yes, try something like this:
```
class State(pc.State):
    text: str

    def clear_input(self):
        self.text = ""

def index():
  return pc.vstack(
      pc.input(value=State.text, on_change=State.set_text),
      pc.button("Clear Input", on_click=State.clear_input),
  )
```

**Comment by asleep-henry** [comment]
Thanks. But if you change the event to `on_blur`, any text doesn't show up in the input.

**Comment by picklelo** [comment]
There's not a way to do it with `on_blur` currently because we can't set the input value programmatically without setting the value. 

We will try to think of a way to do this since it would be handy.

**Comment by masenf** [comment]
Also, if you're using an `rx.form`, you can pass `reset_on_submit=True`; although this doesn't work for some of the more exotic elements, like a pininput
