### ISSUE TITLE
Stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by Iced0368** [pynecone-io/pynecone#282]
**Describe the bug**
When characters such as Chinese characters and Hangul are initially rendered, they are converted into invalid characters and entered in index.js. Therefore, a stream did not contain valid UTF-8 error occurs.

For example:
```
def index():
    return pc.container(
        pc.text("한글")
    )

app = pc.App()
app.add_page(index)
app.compile()
```
this code makes an error

```
class State(pc.State):
    text = "한글"

def index():
    return pc.container(
        pc.text(State.text)
    )

app = pc.App(state=State)
app.add_page(index)
app.compile()
```

but this works.
This obviously looks like a bug.

**Screenshots**
![invalid](https://user-images.githubusercontent.com/103271471/213213765-b5fc0353-9138-4b2d-aabd-945d87047282.png)

index.js when the first code was compiled

** Specifics (please complete the following information):**
 - Python Version: 3.10.xx
 - Pynecone Version: 0.1.12
 - OS: Windows

**Comment by martiniifun** [comment]
I think my problem is similar.
I wrote Pynecone's "To-do List" demo in your gallery.
The placeholder on <Input> component, almost hangul characters go like
![image](https://user-images.githubusercontent.com/62679294/213522276-55de5daf-7651-4170-97a2-3bb73ca45b45.png)

**Comment by nice2cu1** [comment]
same quetision.I use Chinese to display the text and I hope to be able to solve this problem as soon as possible. @Alek99

**Comment by LumiaGG** [comment]
I have a similar problem.After hard coding Chinese in the .py, then the compiled Corresponding Chinese of .js is garbled.

**Comment by Alek99** [comment]
Fix will be push soon this is the pr https://github.com/pynecone-io/pynecone/pull/332

**Comment by DeathShort** [comment]
The bug is caused by pynecone.components.tags.tag ,when format the props, the json.dumps function user ascii encode as default. The solution is add 'ensure_ascii=False' in every case of json.dumps uses.
For example, change the code
 ` return json.dumps(prop.full_name)`
 to 
`return json.dumps(prop.full_name, ensure_ascii=False)`
