### ISSUE TITLE
an internal error with NextJS link object getting multiple children

### ISSUE THREAD

**Issue by abdulrahman-2005** [pynecone-io/pynecone#283]
so i just did `pc init` and then `pc run` with no modifications, but something wrong happens with the link throwing an ERROR ```Error: Multiple children were passed to <Link> with "href" of "YOUR_DOCS_LINK" but only one child is supported https://nextjs.org/docs/messages/link-multiple-children```

once the `pc.link()` was removed from your file defaults it works, hope you solve that because links basically don't work

**Comment by Alek99** [comment]
Are you in windows see here https://github.com/pynecone-io/pynecone/issues/113. We do not support windows yet.
