### ISSUE TITLE
Accordian does not collapse

### ISSUE THREAD

**Issue by mbbrodie** [pynecone-io/pynecone#3]
https://pynecone.io/docs/library/disclosure/accordion

**Comment by Alek99** [comment]
Great to hear from you Mike! Thanks for taking a look at our framework and for pointing this out. I forgot to add the allow_toggle method to be True here, which will allow the example to collapse. I'll make this default to True in our initial release to you don't have to manually add this every time in the future.

**Comment by Alek99** [comment]
Resolved with new pynecone release.
