### ISSUE TITLE
[BUG] wrong typing in the BaseVar that result from a pc.foreach() 

### ISSUE THREAD

**Issue by Lendemor** [pynecone-io/pynecone#302]
**Describe the bug**
When using `pc.foreach()` with a list of `str` as iterable input, the BaseVar that you obtain for rendering does not possess the correct type

**To Reproduce**
```
def minimal_test():
    return pc.vstack(
        pc.foreach(
            ["aa", "bb"], 
            lambda value: pc.markdown(value)
        )
    )
```

**Expected behavior**
Should display correctly the elements from the list, instead crash during compilation 

 
**Additional context**
In the `value` variable, `type_` should be `str`:
`ic| value: BaseVar(name='_', type_=typing.Any, state='', is_local=True, is_string=False)`

I used `pc.markdown` for the example as it currently only accept str rather than BaseVar (see #293 ) but the issue lie in the `pc.foreach` output.

**Specifics:**
 - Python Version: 3.10
 - Pynecone Version: 0.1.13
 - OS: Ubuntu 22.04

**Comment by picklelo** [comment]
This works for me now - I think it was related to [this bug](https://github.com/pynecone-io/pynecone/issues/293) of not allowing vars too be passed to pc.markdown. Please reopen if you still see this.
