### ISSUE TITLE
when passing argument in Event chain, argument type is converted. (int->str)

### ISSUE THREAD

**Issue by wbfw109** [pynecone-io/pynecone#342]
**Describe the bug**
"int" type argument is converted to "str"in Event chain (but value is same when re-convert to int type)

```TypeError: list indices must be integers or slices, not str```

**To Reproduce**
I have written code while refer to https://pynecone.io/docs/state/events

1. App State
```
class State(pc.State):
    is_expanded_list: list[bool] = [False for _ in range(100)]

    def chain_b(self, index: int) -> None:
        print(index, type(index))
        self.is_expanded_list[index] = not self.is_expanded_list[index]

    def chain_a(self, index: int):
        return self.chain_b(index)
```

2. in a component keyword
```on_click=lambda x: State.chain_a(current_index)```

**Expected behavior**
arguments type must not be converted to other type during Event chain.

**Screenshots**
![image](https://user-images.githubusercontent.com/37881026/214705947-6a447294-3318-4f14-89dc-6013f3539434.png)

**Specifics (please complete the following information):**
 - Python Version: 3.11.0
 - Pynecone Version: pynecone-io = "0.1.13"
 - OS: WSL Ubuntu 22.04 distribution in Windows 11 Version 21H2 (OS Build 22000. 1455)
 - Browser (Optional): Edge Browser
 - Shell: Fish shell
 - Node Version: 18.12.1

**Additional context**

**Comment by Alek99** [comment]
Seem like a similar issue to this https://github.com/pynecone-io/pynecone/issues/336
