### ISSUE TITLE
Can you please add an 'Autocomplete' component?

### ISSUE THREAD

**Issue by heumsi** [pynecone-io/pynecone#345]
**Describe the bug**

I know there is no "Autocomplete" component by default in Chakra UI.

However, I can add an Autocomplete component through the library below.

https://github.com/koolamusic/chakra-ui-autocomplete

Could you possibly support this component in Pynecone?

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:
 - Pynecone Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by Alek99** [comment]
Yes I think we need to update our chakra version but we can add this

**Comment by masenf** [comment]
Duplicate of #239
