### ISSUE TITLE
Arguments on the method passed to on_click created undefined variable on the generated JS code

### ISSUE THREAD

**Issue by TommyDew42** [pynecone-io/pynecone#354]
**Describe the bug**
If we pass to `on_click` a state method with args more than just `self`, the generated JS code would have an undefined `_e` variable. And an error `ReferenceError: _e is not defined` would be thrown when we click the component with the `on_click` function.

**To Reproduce**
Clicking on the button from the browser would throw an JS error.
```py
class State(pc.State):
    def some_action(self, value):
        pass

def index():
    return pc.button("button", on_click=State.some_action)

app = pc.App(state=State)
app.add_page(index)
app.compile()
```

The generated JS code:
```jsx
<Button onClick={() => Event([E("state.some_action", {value:_e})])}>{`button`}</Button>
```

**Expected behavior**
An error during compilation step should be thrown to show this error
Or there shouldn't be any error on the JS side e.g. by getting the `_e` from the `onClick` function.

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:
 - Pynecone Version: 0.1.13
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by j-min** [comment]
Having same issue with `on_click`, in pynecone - 0.1.14 / Mac OSX
