### ISSUE TITLE
Feature Request PDF show.

### ISSUE THREAD

**Issue by Shahin-rmz** [pynecone-io/pynecone#394]
Hello,
I just want to show pdfs in pages of my app.
How is that possible?
Thanks.

**Comment by Lendemor** [comment]
It is already possible using `pc.box`.

```
pc.box(element="embed", src="test.pdf", width="100%")
```
and by putting test.pdf in your `assets` folder

**Comment by Shahin-rmz** [comment]
Thanks so much.
Sorry for wrong question.
