### ISSUE TITLE
ERROR:    [Errno 98] Address already in use

### ISSUE THREAD

**Issue by Anti-Apple4life** [pynecone-io/pynecone#400]
**Describe the bug**
When running the demo app, this error appears, and the terminal does not have control over the process anymore, although it still is active and works. Both localhost:3000 and localhost:8000 are available.
**To Reproduce**
install pynecone-io
pc init
pc run
**Expected behavior**
I expect this message to not appear and for the pc process to be in the foreground.
**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: Python 3.10.9
 - Pynecone Version:　0.1.13
 - OS: Arch
 
**Additional context**

**Comment by FHU-yezi** [comment]
We will release a new version which contains some fix about this problem, please try and tell us whether this problem can be resolved.

**Comment by Alek99** [comment]
Exactly the v0.1.14 should have functionally to resolve this in 2 ways.

1. We have added code that makes sure the ports are terminated on exit of the `pc run`
2. If something is running on the ports it is trying to use for the frontend and backend it will ask the user if they want to terminate the processes running on those ports. If the user says yes it will terminate those processes and your pynecone app will start. If the user says no it will exit from the `pc run` leaving those processes still running.

**Comment by Alek99** [comment]
Feel free to reopen if this issue still persists in v0.1.14 and I'll take another look

**Comment by HellAmbro** [comment]
Fixed #417
