### ISSUE TITLE
websocket connection issue at production mode

### ISSUE THREAD

**Issue by DongyoungKim2** [pynecone-io/pynecone#403]
**Describe the bug**
Following self-hosting manual @ https://pynecone.io/docs/hosting/self-hosting, `api_url` will fail to connect websocket due to the protocol prefix missing. (i.e. 192.168.1.1:8000(X) -> ws://192.168.1.1:8000 (O)

**Additional context**
Please fix either documentation or `const EVENT = "ws://192.168.1.1:8000/event"` in `.web/pages/index.js`

**Comment by Alek99** [comment]
Ok thanks we will fix the docs to include this
