### ISSUE TITLE
Allow client states

### ISSUE THREAD

**Issue by julien777z** [pynecone-io/pynecone#406]
Right now the states are saved on the server, so if I refresh the page, the previous state is still intact.

I don't always want this, for example, I may want to make a calculator app that every time I refresh the page, the history and state are blank.

This would also be consuming a lot of memory for bigger applications if everything is saved to the server.

**Comment by Alek99** [comment]
Yes this is defiantly possible to implement will look into it

**Comment by picklelo** [comment]
I think for this use case you can use an `on_load` event where you call `self.reset()` which should reset the state.
