### ISSUE TITLE
Add anchor tag component

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#416]
We need a way to have anchor tags so you can navigate to a particular section of a page.

For example on our doc pages, you could then link a specific subsection.

**Comment by PeterYusuke** [comment]
Hi!
Do you mind if I work on this issue?
I’m new to React thou.

**Comment by picklelo** [comment]
Yes for sure! I don't have much experience in how to do this, but feel free to start and you can always hop on our Discord to brainstorm ideas or get help.

**Comment by dhawalpatil200** [comment]
But there is already Link component for navigation ? Are there any other use case by adding anchor tag component ?
