### ISSUE TITLE
When using skeleton's is_loaded with State, it does not become True.

### ISSUE THREAD

**Issue by heumsi** [pynecone-io/pynecone#422]
**Describe the bug**

When using skeleton's is_loaded with State, it does not become True.

**To Reproduce**
 - Code/Link to Repo:

Part of my code is below.

```python
class QueryState(BaseState):
    labels: List[str] = []
    taints: List[str] = []
    nodes: List[str] = api.get_nodes()
    is_loaded: bool = False

    def refresh_nodes(self):
        self.is_loaded = False
        self.nodes = api.get_nodes(self.labels, self.taints)
        self.is_loaded = True

pc.box(
	pc.button(
	    pc.icon(tag="Refresh"),
	    color_scheme="green",
	    on_click=[
	        QueryState.refresh_nodes,
	    ],
	)
	pc.box(
	    pc.foreach(
	        QueryState.nodes,
	        lambda node: pc.box(
	            pc.skeleton(
	                pc.text(node),
	                is_loaded=QueryState.is_loaded,
	            ),
	        ),
	    ),
	)
)
```

<img width="1308" alt="image" src="https://user-images.githubusercontent.com/31306282/216043467-69914640-6786-43d7-83a0-a3a0e9f5aa57.png">

When `refresh_nodes() `is called, `is_loaded` of `QueryState` should be changed to `False` and then changed back to `True`.

However, if I check the page, it still seems that the skeleton is only left with `is_loaded=False`.
Even though the `QueryState.nodes` value is filled in, the value does not appear and only the skeleton box still appears.

What's the matter? How can I solve this?

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
- Python Version: 3.11.0
- Pynecone Version: 0.1.14
- OS: Mac OS Monetrey 12.6
- Browser (Optional): Chrome 109.0.5414.87 arm 64
 
**Additional context**

**Comment by masenf** [comment]
In the latest `reflex == 0.2.0`, you can `yield` from event handlers to trigger a state update, while continuing to process on the backend. This is very useful when showing loading indicators for long running operations.

Please see **Yielding Multiple Updates** on the [State > Events](https://reflex.dev/docs/state/events) page in the docs.

With the following code, when I click refresh, I can see the skeleton loading for a second, then displays the values `a b c`. Note the use of `yield` inside `refresh_nodes`.

```python
import time
from typing import List

import reflex as rx


def get_nodes(*args, **kwargs) -> List[str]:
    time.sleep(1)
    if args:
        return ["a", "b", "c"]
    return ["initial"]


class QueryState(rx.State):
    labels: List[str] = []
    taints: List[str] = []
    nodes: List[str] = get_nodes()
    is_loaded: bool = False

    def refresh_nodes(self):
        self.is_loaded = False
        yield
        self.nodes = get_nodes(self.labels, self.taints)
        self.is_loaded = True


def index():
    return rx.box(
        rx.button(
            rx.icon(tag="repeat"),
            color_scheme="green",
            on_click=[
                QueryState.refresh_nodes,
            ],
        ),
        rx.box(
            rx.foreach(
                QueryState.nodes,
                lambda node: rx.box(
                    rx.skeleton(
                        rx.text(node),
                        is_loaded=QueryState.is_loaded,
                    ),
                ),
            ),
        ),
    )


# Add state and page to the app.
app = rx.App(state=QueryState)
app.add_page(index)
app.compile()
```
