### ISSUE TITLE
Websocket was closed meanwhile asyncio tasks is running

### ISSUE THREAD

**Issue by JeremyLG** [pynecone-io/pynecone#424]
**Describe the bug**
When you minimize your web page or go to another application, if you had any asyncio tasks running then your app will crash in the background.
Meaning that on the UI side, you have no feedback, everything seems to be ok but your app is now frozen and you can't do anything on it.
And you have to force refresh the page for it to work again. You can see the specific logs :
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
...
...
...
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
```

**To Reproduce**
 - [Clock project example](https://github.com/pynecone-io/pynecone-examples/tree/main/clock)
 - ```pc init```
 - ```pc run```
 - Enable the switch ON to start the clock
 - Minimize your web browser or go to another app while the clock is running
 - Come back to the web browser clock page
 - Check your ```pc run``` logs and you will see the error and the clock will be stuck

**Expected behavior**
I dunno if this is expected behavior but I think background asyncio running tasks shouldn't make the UI crash if you leave the page.

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.10
 - Pynecone Version: 0.1.14
 - OS: WSL2
 - Browser (Optional): Edge

**Comment by advo-kat** [comment]
There’s a related problem on mobile. If you leave the browser it will often close the websocket connection. If there was a back-end task pending the result will not be received if the front-end misses it and the front-end will be stuck waiting for a response. Only upon reload will the fresh updated state be available to the front end.

**Comment by JeremyLG** [comment]
I mean I was testing on my windows PC and I don't know if you tried to reproduce the steps in order to see the logs but you'll see if you're in debug mode that :
- First when you leave the tab like for example you minimize your web browser where you started the clock
- Then you can see in the logs that your state is still being updated in the background, so our websocket connection wasn't closed and is still running the asyncio tick task :
```
DEBUG:    > TEXT '{"delta": {"state": {"second_display": "28", "h...": {}, "payload": {}}]}' [373 bytes]
DEBUG:    < TEXT '{"token":"683b65c7-5e5b-4479-c96c-e0c2fc8ae570"...uery":{}},"payload":{}}' [123 bytes]
DEBUG:    > TEXT '{"delta": {"state": {"second_display": "29", "h...": {}, "payload": {}}]}' [373 bytes]
DEBUG:    < TEXT '{"token":"683b65c7-5e5b-4479-c96c-e0c2fc8ae570"...uery":{}},"payload":{}}' [123 bytes]
DEBUG:    > TEXT '{"delta": {"state": {"second_display": "30", "h...": {}, "payload": {}}]}' [373 bytes]
DEBUG:    < TEXT '{"token":"683b65c7-5e5b-4479-c96c-e0c2fc8ae570"...uery":{}},"payload":{}}' [123 bytes]
```
- BUT when you come back to the app (the webpage), then our websocket instantly gets re-initialized and you see this log :
```
DEBUG:    < CLOSE 1000 (OK) [2 bytes]
DEBUG:    = connection is CLOSING
DEBUG:    > CLOSE 1000 (OK) [2 bytes]
DEBUG:    x half-closing TCP connection
DEBUG:    = connection is CLOSED
DEBUG:    = connection is CONNECTING
```
- And as you can see with the last line of code, the websocket is re-connecting but it will be a new one and it lost track of our running asyncio tick task :
```
INFO:     connection open
DEBUG:    = connection is OPEN
ERROR:    Exception in ASGI application
Traceback (most recent call last):
...
...
...
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
INFO:     connection closed
```
