### ISSUE TITLE
Create XML Sitemap

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#425]
We should generate [sitemaps](https://nextjs.org/learn/seo/crawling-and-indexing/xml-sitemaps) for every app by default. This should help a lot with SEO (I think this is also why the main pynecone.io website isn't indexed by Google outside of the home page)

**Comment by advo-kat** [comment]
Could there be functionality to also enumerate dynamic routes? For example on a blog with article id’s you’d want to use dynamic routes but also have each article on the site map.
