### ISSUE TITLE
Button no response

### ISSUE THREAD

**Issue by EscaticZheng** [pynecone-io/pynecone#426]
**Describe the bug**
![image](https://user-images.githubusercontent.com/107376080/216242081-801e5bca-690b-4bfc-aae9-0f250564aeb9.png)
I copy the dalle example, when I click the button, no response at all, no blue circle, no picture and check server in dev mode, still nothing in background.
![image](https://user-images.githubusercontent.com/107376080/216243456-57105f9f-1cbe-492e-856f-bfb0ab9bf455.png)
I can use my api key get the picture in local, so not the api problem.
**To Reproduce**
just copy the dalle example, init and run it.
 - Code/Link to Repo:
Example Pynecone App
https://github.com/pynecone-io/pynecone-examples/tree/main/dalle
**Expected behavior**
It should appear the circle then wait to see the picture.
**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:3.8.10
 - Pynecone Version:0.1.14
 - OS: Ubuntu 20.04
 - Browser (Optional): All the Browser
 - Nodejs:v18.13.0
 
**Additional context**

**Comment by Alek99** [comment]
Did you put your own api key in the app?

**Comment by EscaticZheng** [comment]
> Did you put your own api key in the app?

Yes.

**Comment by EscaticZheng** [comment]
![image](https://user-images.githubusercontent.com/107376080/216518976-63bcf55d-5a61-48f2-b0e3-bd05e7bf4d7d.png)

**Comment by Alek99** [comment]
Ah ok seems to be working for me anyone else getting this issue? Also is you api response coming back as successful?

**Comment by EscaticZheng** [comment]
> Ah ok seems to be working for me anyone else getting this issue? Also is you api response coming back as successful?

I can use my api in local. But the point is I click the button, nothing happened. Even I add print(111111) to "def get_image(self)", It can not print anything.It seems Click The Button does not trigger the get_image function.............

**Comment by Alek99** [comment]
Ok ill try and look into it more tomorrow, maybe an issue with v 14

**Comment by mengcius** [comment]
I had the same problem, I was fine on the local wsl(ubuntu20), but nothing happened on the cloud server.

**Comment by mengcius** [comment]
A strange phenomenon, when I was running the cloud server and the local simultaneously, when I clicked the button in the cloud, the local actually responded.
In addition, pc.switch has the same problem.

**Comment by mengcius** [comment]
> Ok ill try and look into it more tomorrow, maybe an issue with v 14

Is there any progress? Is it because some of the libraries aren't properly loaded?

**Comment by mengcius** [comment]
I have solved this problem by configuring `pc.Config(api_url="http://<public IP>:8000")`, the IP address must be a public IP address.

**Comment by localhd** [comment]
@mengcius I have the same problem. Do you mean aws public IPv4 by api_url="http://<public IP>:8000"?

**Comment by mengcius** [comment]
> 

yes

**Comment by mengcius** [comment]
> @mengcius I have the same problem. Do you mean aws public IPv4 by api_url="http://:8000"?

yes

**Comment by masenf** [comment]
The frontend must be able to reach the backend via websocket, or no interactivity can occur.

Ensure that
* backend is running
* `api_url` is set to a public IP where the backend server is accessible (include port)
* no websocket errors are displayed in browser devtools
