### ISSUE TITLE
Can't expose fastapi backend api following pynecone document

### ISSUE THREAD

**Issue by Benjamin-Shengming** [pynecone-io/pynecone#427]
**Describe the bug**
Can't access fastapi api route

**To Reproduce**
copy code from here
[ - Code/Link to Repo:](https://pynecone.io/docs/advanced-guide/api-routes)

**Expected behavior**
return json object  same as document

**Screenshots**
![image](https://user-images.githubusercontent.com/35768762/216251012-5c2569ce-185a-400c-b1a1-b9ce9ab23ac6.png)

** Specifics (please complete the following information):**
 - Python Version: 3.10.9
 - Pynecone Version: 0.1.14
 - OS:  manjaro
 - Browser (Optional): firefox/edge
 
**Additional context**
try to build a web system for both human and other systems with restful api.

**Comment by Benjamin-Shengming** [comment]
Just guessing: 
  is that caused by nextjs routing which does not allow that path?

The index page works fine if I use add_page(Index)

**Comment by picklelo** [comment]
The FastAPI server is exposed on port `8000` (while the NextJS app is on port `3000`).

Does it work if you go to localhost:8000/items/23 ?

**Comment by Benjamin-Shengming** [comment]
@picklelo  
you are right, the 8000 port does have everything  :100: , thx
Can close this issue I think.

And using decorator way is more like fastapi style.    

![image](https://user-images.githubusercontent.com/35768762/216294761-771a2d3b-bc1d-4bba-a45b-8b0763de5ad6.png)

**Comment by Lendemor** [comment]
In general I would agree that using the decorator is neater.

In this case however it means you would have to write all your API endpoints between the `app = pc.App(state=State)` and `app.compile()`, and doing that just so we can use the decorator feel counter-productive.
