### ISSUE TITLE
Question : How can I conditionally render a render page

### ISSUE THREAD

**Issue by bong199119** [pynecone-io/pynecone#439]
I want to render different pages depending on conditions (login information). I looked through the documentation but couldn't find anything related to it. (Please let me know if you have any)

The reason for writing this code is to prevent direct access to the url by users who do not have a pin number.

Please let me know if there is any other way

![image](https://user-images.githubusercontent.com/57978796/216753620-9bd4e8fd-523d-47ef-9445-d23daf53ca46.png)

Is it possible to get the value when importing a variable in the form of class.var? In the image above, the state.login value is either 'login' or 'logout'. If you fetch via state.login, you cannot get string.

For example, is there a function like the .string function of the beautifulsoup library that is used when parsing xml?

**Comment by picklelo** [comment]
See here: https://pynecone.io/docs/library/layout/cond

Any time you want to use a state var, you should use `pc.cond` instead of Python if/else.
Similarly if you want to iterate over a state var, use `pc.foreach` instead of a Python for loop.

Hope that helps!
