### ISSUE TITLE
Question : Page Load Events

### ISSUE THREAD

**Issue by bong199119** [pynecone-io/pynecone#442]
I tried to find the description of 'Page Load Events' in https://pynecone.io/docs/components/pages and applied it. But I got the following error

app.add_page(indext, title="SMS", on_load=CollatzState.start_collatz)
TypeError: add_page() got an unexpected keyword argument 'on_load'

The code used is below.

![image](https://user-images.githubusercontent.com/57978796/216781369-b213e9db-83a3-42a4-9115-bb5d44fdc29a.png)

Did I misunderstand how to use it? Or is it a version issue? I would be grateful if you could tell me if there is a different problem.

**Comment by Alek99** [comment]
Are you on v0.1.14? It was added in the last release
