### ISSUE TITLE
Dynamic routes don't seem to work as described in docs

### ISSUE THREAD

**Issue by simonmesmith** [pynecone-io/pynecone#458]
**Describe the bug**
I tried to implement dynamic routes as described here: https://pynecone.io/docs/components/pages. It does not seem to work.

**To Reproduce**
- Follow instructions at https://pynecone.io/docs/components/pages to implement dynamic routes, and it does not seem to work

**Expected behavior**
It should work as described.

**Screenshots**

base_state.py
```python
import pynecone as pc

class BaseState(pc.State):
    user_id: int
    logged_in: bool = False

    def logout(self):
        """Log out a user."""
        self.reset()
        return pc.redirect("/")
```

router.py
```python

import pynecone as pc
from .base_state import BaseState
from .post import post

app = pc.App(state=BaseState)
app.add_page(post, route="/post/[pid]")

app.compile()
```

post.py
```python
import pynecone as pc
from .base_state import BaseState

class PostState(BaseState):
    @pc.var
    def post_id(self):
        return self.get_query_params().get("pid", "no pid")

def post():
    return pc.heading(PostState.post_id)
```

The above yields "no pid."

**Specifics (please complete the following information):**
 - Python Version: 3.10.8
 - Pynecone Version: 0.1.14
 - OS: macOS Monterey 12.6.2
 
**Additional context**
I tried this multiple times and cannot get it to work. I'm not sure if I'm doing it properly but I tried to follow the documentation exactly and even created post stuff just to mirror the example exactly, and it didn't work.

**Comment by Lendemor** [comment]
Do you also have "no pid" if you do all this logic in the same BaseState?

Might be a bug related to states subclassing.

**Comment by simonmesmith** [comment]
Yeah, same issue.

I can get this to work in a very simplified situation where everything happens within the same .py file.

But in a more complex implementation, such as with a separate base_state file, I cannot get it to work.

I'm not sure what's going wrong. If I figure it out I can post here.

**Comment by simonmesmith** [comment]
Today I experimented with this further. There appears to be a weird bug, at least in my testing, where dynamic variables longer than three characters don't work. For example, /post/[lug] worked but /post/[slug] didn't. I'm not sure if this is just me or if someone else can confirm.
