### ISSUE TITLE
PageUp button

### ISSUE THREAD

**Issue by Aarize29** [pynecone-io/pynecone#460]
**Describe the bug**
Helps to directly navigate to the top of the web page

**Comment by Aarize29** [comment]
May I add this feature?

**Comment by picklelo** [comment]
Sure! Do we need to wrap a new React component for this, or how would it work?

**Comment by Aarize29** [comment]
Yaah, we can add a new component or we can directly add a button in bottom right corner, if we click on that button we will redirect to  top of the page, we can add few stylings also to make the UI better

**Comment by masenf** [comment]
Will work on this generalizing this functionality in #1122
