### ISSUE TITLE
Allow for the returning of functions in the page on_load function.

### ISSUE THREAD

**Issue by Cheesy-Brik** [pynecone-io/pynecone#471]
Currently when returning a function to the on_load kwarg in the add_page function, it does not trigger the function. Meaning a function that is called on_load cannot call other functions (unlike functions called by components).

**Comment by masenf** [comment]
The following code is working for me on `reflex == 0.2.0`

```python
import time

import reflex as rx


class State(rx.State):
    status: str = ""

    def chain(self):
        time.sleep(1)
        self.status = "chain"

    def on_load(self):
        self.status = "on_load"
        return self.chain


def index() -> rx.Component:
    return rx.heading(State.status)


app = rx.App(state=State)
app.add_page(index, on_load=State.on_load)
app.compile()
```

Please reopen with example code if you're still having issues with the latest release.
