### ISSUE TITLE
[Bug] Cannot export on Windows due to zip command

### ISSUE THREAD

**Issue by Cheesy-Brik** [pynecone-io/pynecone#472]
**Describe the bug**
```
'zip' is not recognized as an internal or external command,
operable program or batch file.
```
Getting this error when trying to export, it says the files have been made but they aren't at the path it says they are so I assume it doesn't actually make them.

Windows 10, python 3.10.6

**Comment by r0b2g1t** [comment]
Which command parameters do you use to export?

**Comment by picklelo** [comment]
This is from running `pc export` - I think this issue is that `zip` doesn't exist on Windows - we need some alternative.

**Comment by r0b2g1t** [comment]
Yes, it need zip as a command to export. I have also recognised that you can't disable zip for export.

**Comment by r0b2g1t** [comment]
Maybe a PR which allows to read a parameter for enable of disable zip. Like the frontend and backend params for run.

I will try to create the PR tomorrow.

**Comment by Alek99** [comment]
> Maybe a PR which allows to read a parameter for enable of disable zip. Like the frontend and backend params for run.
> 
> I will try to create the PR tomorrow.

Thanks let me know if this fixes this issue

**Comment by r0b2g1t** [comment]
@Alek99, @Cheesy-Brik and @picklelo. I have create the PR #479 which includes the optional parameter to disable zipping.

**Comment by Cheesy-Brik** [comment]
> @Alek99, @Cheesy-Brik and @picklelo. I have create the PR #479 which includes the optional parameter to disable zipping.

@r0b2g1t I raise you one better, exact same command but refactored for windows 
```
powershell -Command "Set-Location .web/_static; Compress-Archive -Path .\* -DestinationPath ..\..\frontend.zip; Set-Location ..\..; Compress-Archive -Path .\* -DestinationPath backend.zip -Exclude .web\*, assets\*, frontend.zip, backend.zip"
```
Should be added in https://github.com/pynecone-io/pynecone/blob/main/pynecone/utils.py#L502 using os.name == 'nt' to check for windows.

**Comment by r0b2g1t** [comment]
That's awesome, I will take a look for integration it by identify the the os. thanks. :-)

**Comment by r0b2g1t** [comment]
@Cheesy-Brik I have add the powershell command and also the os check.
