### ISSUE TITLE
Resolve circular imports

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#478]
There are a couple places in the code where we circumvent circular imports by importing within a function. We should refactor to avoid this and move all imports to the top of files if possible.

**Comment by r0b2g1t** [comment]
I have also found some imports they are unused. If I have time I will do an cleanup PR.

**Comment by r0b2g1t** [comment]
I have create a PR #498 with two types of fixes. :-) I didn't find circular imports.

**Comment by Alek99** [comment]
I think this is resolved.
