### ISSUE TITLE
Don't show stack traces in prod

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#48]
Currently if the event handler throws and exception, the stack trace is alerted on the browser. We should keep this enabled in dev mode, but have a cleaner solution when running in production.

https://softwareengineering.stackexchange.com/questions/162007/should-a-stack-trace-be-in-the-error-message-presented-to-the-user

**Comment by FHU-yezi** [comment]
Maybe we can make the error message more friendly to the user? Just check the Pull Request, change the error message to this will be better:

> Some thing we dont't like has happend. Please refresh this page and try again later.

**Comment by picklelo** [comment]
I can make a more detailed error message in a follow up.
