### ISSUE TITLE
Possible wrong name in ResponsiveGrid doc

### ISSUE THREAD

**Issue by Lendemor** [pynecone-io/pynecone#49]
On the doc page for [ResponsiveGrid](https://pynecone.io/docs/library/layout/responsivegrid), there is the following text:

> SimpleGrid provides a friendly interface to create responsive grid layouts with ease. SimpleGrid composes Box so you can pass all the Box props and css grid props with addition to the ones below.

SimpleGrid is not mentionned anywhere else, shouldn't it be ResponsiveGrid?

**Comment by Alek99** [comment]
Ok just updated this, we are deploying a new website tonight so it should be updated on the live site soon.
