### ISSUE TITLE
Hard code bun version

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#491]
Currently we always download the latest bun, which could lead to issues. We should have a fixed version.

**Comment by PrerithSubramanya** [comment]
in case of manually installing bun use the following command:
RUN curl -fsSL https://bun.sh/install | bash -s -- bun-v0.5.5

**Comment by Cheesy-Brik** [comment]
Incompatible with windows, won't be able to use this command for windows in the actual repo

**Comment by FHU-yezi** [comment]
> Incompatible with windows, won't be able to use this command for windows in the actual repo

We use Node.js instead of bun on Windows.

**Comment by Cheesy-Brik** [comment]
> > Incompatible with windows, won't be able to use this command for windows in the actual repo
> 
> We use Node.js instead of bun on Windows.

Makes sense, disregard my comment then :)
