### ISSUE TITLE
PC Export but only frontend? 

### ISSUE THREAD

**Issue by ngmisl** [pynecone-io/pynecone#496]
Is there a way to only export the static site? At the moment backend and frontend are exported and tied together. Deploying only the frontend gives out some api errors in the console

**Comment by r0b2g1t** [comment]
Currently it is not possible to export only backend or frontend. Maybe would be a good idea for a PR.

**Comment by picklelo** [comment]
Yup this would be a great feature to add - we can add flags similar to `pc run` called `--no-frontend` and `--no-backend`.

We should also switch these flags at some point to `--frontend-only` and `--backend-only` since that's probably clearer. But we should be consistent throughout the commands.

**Comment by r0b2g1t** [comment]
The PR #499 with the feature is created. 😊

**Comment by picklelo** [comment]
This should be available now that #499 is merged 😃
