### ISSUE TITLE
Setting the value of an input to a pc.computed does not work

### ISSUE THREAD

**Issue by kbrgl** [pynecone-io/pynecone#5]
**Describe the bug**
In the [Computed Vars example](https://pynecone.io/docs/state/vars), I tried changing the `pc.heading(UppercaseState.upper_text)` to `pc.input(value=UppercaseState.upper_text)` but this does not work. It does not work when I set this "computed input" to be controlled, either.

**To Reproduce**
(Described above.)

**Expected behavior**
I expected this to work, since setting the value of one input to the output of another input is not uncommon. I would then have tried to use an `on_change` handler on the computed input to store if the user edited the translation output and what they edited it to. (I had a similar use case in the research study interface I’d demoed.)

**If on Desktop (please complete the following information):**
Firefox 106 on macOS Monterey.

**Comment by Alek99** [comment]
Architecture changed closing.
