### ISSUE TITLE
Implement Numba (JIT Compiling) natively into pynecone

### ISSUE THREAD

**Issue by Cheesy-Brik** [pynecone-io/pynecone#505]
Since you're most likely recalling event functions a ton, might as well take advantage of some JIT for performance gains (especially in large apps)

**Comment by FHU-yezi** [comment]
Currently our bottle neck of performance is network lag and front-end repaint.

**Comment by kbrgl** [comment]
Numba wouldn't help here, since we don't have any heavy number crunching code (or indeed any code that would benefit from vectorization or SIMD).
