### ISSUE TITLE
Allow union types in `utils._issubclass`

### ISSUE THREAD

**Issue by TommyDew42** [pynecone-io/pynecone#511]
**Describe the bug**
`utils._issubclass` doesn't allow the cls_base to be a union type.

**To Reproduce**

 Let's say we change [Foreach](https://github.com/pynecone-io/pynecone/blob/5e0d5b9e2e2aec9bdf19dd75629bfcef26a33f6a/pynecone/components/layout/foreach.py#L11-L15) to:
 ```py
class Foreach(Component):
    """A component that takes in an iterable and a render function and renders a list of components."""

    # The iterable to create components from.
    iterable: Var[List] | List # <----- change
```

There will be an error in [utils._issubclass](https://github.com/pynecone-io/pynecone/blob/5e0d5b9e2e2aec9bdf19dd75629bfcef26a33f6a/pynecone/utils.py#L147):
```
...
pynecone/components/component.py:69: in __init_subclass__
    if utils._issubclass(field.type_, Var):
pynecone/utils.py:164: in _issubclass
    return cls_check_base == Any or issubclass(cls_base, cls_check_base)
<frozen abc>:123: in __subclasscheck__
    ???
E   TypeError: issubclass() arg 1 must be a class
```

**Expected behavior**
We should allow union type.

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 1.15
 - OS: 
 - Browser (Optional):
 
**Additional context**
Probably we want to have sth like this in `utils._issubclass`:
```py
   # ...
    cls_bases = cls_base if isinstance(cls_base, tuple) else (cls_base,)
    return cls_check_base == Any or any(
        issubclass(base, cls_check_base) for base in cls_bases
    )
```

**Comment by PeterYusuke** [comment]
Just info. 
Union type with “|” is not allowed under Python 3.9. 
In ci test, I failed.
We need to find another way.
