### ISSUE TITLE
Production mode not working on Windows OS

### ISSUE THREAD

**Issue by LiteEagle262** [pynecone-io/pynecone#515]
**Describe the bug**
```
import fcntl
ModuleNotFoundError: No module named 'fcntl'
```
Sollution: https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl

**To Reproduce**
Try production mode on windows

**Expected behavior**
Production Mode to work

**Comment by picklelo** [comment]
PR #570 merged and should resolve this
