### ISSUE TITLE
Restarting Pynecone Server

### ISSUE THREAD

**Issue by ImPandax** [pynecone-io/pynecone#522]
**Describe the bug**
Executing `pc run` again right after terminating the previous `pc run` with CTRL+C leads to an error.

> Something is already running on port 3000. This is the port the frontend runs on.

If it asks you to kill it

> Kill it? [y/n]: y

you will get another two errors saying 

> ...

> PermissionError: [Errno 13] assume access denied (originated from automatically set for PID 0)

> ...

> psutil.AccessDenied: (pid=0, name='System Idle Process')

**To Reproduce**

1. open a terminal and `pc run`
2. end execution of step one with CTRL+C
3. restart the program: `pc run`

**Expected behavior**
Terminating the previous execution and restarting it will start everything as expected instead of giving an error.

** Specifics (please complete the following information):**
 - Python Version: Python 3.10.4
 - Pynecone Version: pynecone 0.1.14
 - OS: Windows
 
**Additional context**
The program doesn't get closed properly. After killing it, something is still blocking the port to re-run the program. After some time it closes itself and you can `pc run` again, but you have to wait since you have no permission to kill it.

**Comment by ElijahAhianyo** [comment]
This issue still persists in Pynecone 0.1.18, windows 11. Though its not entirely blocking. You typically need to wait a while to close by itself. Kind of annoying but tolerable
