### ISSUE TITLE
Allow state var to be input to select form

### ISSUE THREAD

**Issue by kkovary** [pynecone-io/pynecone#53]
I might be missing something, but at the moment it seems like state vars cannot be used as inputs to the select form. If possible this would be a really nice feature for creating dynamic dropdown options (for instance values retrieved via API calls).

**Comment by picklelo** [comment]
I'll look into this, seems like a basic feature we should support.

**Comment by Alek99** [comment]
This would be a really cool feature thanks for the suggestion
