### ISSUE TITLE
How to make Sidebars?

### ISSUE THREAD

**Issue by qqkkwan** [pynecone-io/pynecone#557]

**Comment by Alek99** [comment]
This is how we do the side bar on the main website https://github.com/pynecone-io/pcweb/blob/main/pcweb/components/sidebar.py


The main important style props to pass in are

```python
align_items="start",
overflow_y="scroll",
position="fixed",
scroll_padding="4em",
```

**Comment by qqkkwan** [comment]
Are there any plans to make a wrapper for it or provide a pynecone pro framework  including built-in layouts, routing, and more , maybe pynecone admin ：）

**Comment by Alek99** [comment]
I think we will add a built in admin panel eventually, for the pro layout we would probably just open source them.
