### ISSUE TITLE
pc.foreach doesn't work with pc.img

### ISSUE THREAD

**Issue by lucashofer** [pynecone-io/pynecone#561]
**Describe the bug**
I'm trying to display a list of image urls. I'm using the pc.foreach function to iterate through the list of urls. However, the variable passed by the pc.foreach function to the render function throws an error if used in the ``src=`` field for pc.img.

**Steps to reproduce**

Below is the code that throws the error. All the images are present in the assets directory.

```from pcconfig import config
import pynecone as pc


class ForeachState(pc.State):
    urls = [
        "1.png",
        "2.png",
        "3.png",
    ]


def image_box(url):
    return pc.box(pc.image(src=url))


def index():
    return pc.responsive_grid(
        pc.foreach(ForeachState.urls, image_box),
        columns=[2, 4, 6],
    )


# Add state and page to the app.
app = pc.App(state=ForeachState)
app.add_page(index)
app.compile()
```

**Expected behavior**
The following error occurs:
```
TypeError: Invalid var passed for prop src, expected type <class 'str'>, got value _ of type typing.Any.
```

**Specifics**
 - Python Version: 3.10
 - Pynecone Version: 0.1.16
 - OS: Ubuntu 20.04

**Comment by Lendemor** [comment]
```
class ForeachState(pc.State):
    urls: list[str] = ["1.png", "2.png", "3.png"]
```
Can you try this ?

**Comment by lucashofer** [comment]
I implemented this. There are still a few edge cases where Pynecone is able to compile, but the JS code fails in the browser. However, on the whole it solved my issued. Thanks!
