### ISSUE TITLE
Method calling inside State class

### ISSUE THREAD

**Issue by CelaniDe** [pynecone-io/pynecone#567]
**Describe the bug**
Method inside State class can't call another method inside State class

**To Reproduce**

`from pcconfig import config
from random import randint
import pynecone as pc

class State(pc.State):
    """The app state."""
    random_number : int = 0

    def regenerate_random_number(self):
        self.random_number = randint(0,100)
        self.print_new_random_number()

    def print_new_random_number(self):
        print(self.random_number) 

def index():
    return pc.center(
        pc.vstack(
            pc.button("Generate a random number",on_click=State.regenerate_random_number), 
            pc.text("Random Number : " + State.random_number, font_size="2em"),
        ),
        padding_top="10%",
    )

app = pc.App(state=State)
app.add_page(index)
app.compile()`

**Expected behavior**
should have been printed on terminal the new generated number

** Specifics (please complete the following information):**
 - Python Version: 3.10.2
 - Pynecone Version: 0.1.15
 - OS: Windows
 - Browser (Optional): Chrome

**Comment by Lendemor** [comment]
It's because they are transformed in EventHandler, you can't call them directly.

if you have:
```
class State(pc.State):
    def event1(self):
        pass
    def event2(self):
        pass
```

You should either 
- chain them `on_click=[event1, event2]`
- return another event
```
def event1(self):
    # do event1 
    return self.event2() # follow up with event2
```
- and you can mix it too the two solution above too I think.

**Comment by LumiaGG** [comment]
You can try this：
self.print_new_random_number.fn(self)
