### ISSUE TITLE
Accordion item cannot be closed 

### ISSUE THREAD

**Issue by Lendemor** [pynecone-io/pynecone#58]
Problem:

> When defining an accordion, all the `accordion_panel()` start closed.
> However, once opened, it is impossible to close them again by clicking on their related `accordion_button()`.

Expected:
>    Clicking an `accordion_button()` should close the related `accordion_panel()`.

How to reproduce: 
Use the examples in the documentation at [Accordion](https://pynecone.io/docs/library/disclosure/accordion)

Edit: 

> Oops, according to #3 it's already solved.
> 
> However default behavior for me (and in the doc too) still seems to be that `allow_toggle=False`. 
> I'm using Version : 0.1.8

**Comment by Alek99** [comment]
Ah ok I must have set default back to` allow_multiple=False` somewhere I'll make it default to true, updating this now. Thanks for pointing this out
