### ISSUE TITLE
Open File?

### ISSUE THREAD

**Issue by PoshoDev** [pynecone-io/pynecone#592]
Hello there, 🙂

I'm experimenting with Pynecone for the first time and I have to say that I really love the experience so far. Not needing to create frontend and backend individually for small web projects is a huge advantage. 😁

Right now I'm trying to add a functionality to a small project for uploading files, but I'm not finding anything related to "Open File" in the Docs. Perhaps it's not a feature yet or am I missing something? If it isn't, then how could I go about doing this? By using an HTML component in my script? 🤔

Hope you can help me with this. Keep up the good work! 😁

**Comment by Alek99** [comment]
We have a file upload component coming in the next release that will do this.

**Comment by PoshoDev** [comment]
Oh great! That's very comforting to hear! Thank you very much. 😁

Is there any place where I can keep track of other upcoming features/releases from the project? 🙂

**Comment by picklelo** [comment]
You can check the "Milestones" in the issues to see what we're working on currently. But we will also create a better product roadmap!

**Comment by PoshoDev** [comment]
Thank you! Will surely keep my eyes on this.

Keep up the work, you're all seriously doing God's work. 😁

**Comment by picklelo** [comment]
This is available as of v0.1.19!
