### ISSUE TITLE
"pc run" with error message on Mac

### ISSUE THREAD

**Issue by korea7030** [pynecone-io/pynecone#598]
**Describe the bug**
I got message "TypeError: Cannot read property 'version' of undefined"

**Expected behavior**
typing "pc run". but not working with error message.

**Screenshots**
![스크린샷 2023-02-24 오전 10 29 55](https://user-images.githubusercontent.com/11729029/221070218-e5b7ec50-cf81-4c5a-9686-1fd7aa0c4f2e.png)

** Specifics (please complete the following information):**
 - Python Version: Python 3.9.13
 - Pynecone Version: 0.1.18
 - OS: MacOS Monterey ver 12.4

**Comment by picklelo** [comment]
Could you try downgrading your bun to v0.5.5? We saw some issues with this version

**Comment by chrswp** [comment]
I also have same problem.
OS Linux Debian 11
Python 3.9
Pynecone 0.1.18

![Screenshot from 2023-02-24 18-40-05](https://user-images.githubusercontent.com/667948/221170861-80a508c7-6068-44d0-a39c-17f774c435c4.png)

**Comment by miunun** [comment]
It doesn't work when typing "pc run" in CentOS 7, with error message. I'm not sure I can update glibc to 2.18
`─────────────────────────────────────────────────────────────── Starting Pynecone App ────────────────────────────────────────────────────────────────
──────────────────────────────────────────────────────────── Installing frontend packages ────────────────────────────────────────────────────────────
/root/.bun/bin/bun: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/.bun/bin/bun)
──────────────────────────────────────────────────────────────────── App Running ─────────────────────────────────────────────────────────────────────
/root/.bun/bin/bun: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/.bun/bin/bun)`

**Comment by alitrack** [comment]
I got the error 
```
─────────────────────────────────────────────────────────────────────── Starting Pynecone App ────────────────────────────────────────────────────────────────────────
──────────────────────────────────────────────────────────────────── Installing frontend packages ────────────────────────────────────────────────────────────────────
bun install v0.5.8 (1a25af5e)
error parsing lockfile: Lockfile is missing resolution data
ignoring lockfile
──────────────────────────────────────────────────────────────────────────── App Running ─────────────────────────────────────────────────────────────────────────────
$ next dev
/Users/steven/workspace/pc/.web/node_modules/next/dist/server/config.js:68
                userConfigModule = await import((0, _url).pathToFileURL(path).href);
                                         ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/steven/workspace/pc/.web/node_modules/next/dist/server/next.js:8:38)
error: script "dev" exited with code 1 (SIGHUP)
```
Python Version: Python 3.10.2
Pynecone Version: 0.1.20
OS: MacOS Big Sur ver 11.7.4 
bun: 0.5.8

**Comment by picklelo** [comment]
This should be resolved since hard-coding the bun version.
