### ISSUE TITLE
Is there an on_load event handler for dynamic routes?

### ISSUE THREAD

**Issue by heumsi** [pynecone-io/pynecone#609]
Dynamic routes are very useful and I've been using them well.

However, I would like to have a specific function (event handler) triggered when navigating to a dynamic route. Is there any way to do this?

For example, let's say I defined a dynamic route like this

```
app.add_page(post, route="/posts/[post_id]", on_load=PostState.init)
```

When written like this, we expect it to behave like this

- When we navigate to `/posts/1`, we can call `PostState.init()` to initialize the vars in the state.
- When we move to `/posts/2`, we similarly call `PostState.init()` to initialize the vars in State.

However, for now, the on_load event is only called once in the above scenario, i.e. we don't call `PostState.init()` when we navigate to `/posts/2`.

I don't think I'm calling the on_load event for every dynamic route.

Is there any way to fix this?

**Comment by masenf** [comment]
I propose a new Component which wraps [router.events](https://nextjs.org/docs/pages/api-reference/functions/use-router#routerevents), and exposes the NextRouter events for assignment to state events. To watch for router change states, you would add the component to the view and assign event handlers to it as props.

```python
class State(pc.State):
    post: Post = Post()

    def on_route_change_complete(self):
        self.post = load_post(self.post_id)


def index():
     return pc.vstack(
         pc.router(on_route_change_complete=State.on_route_change_complete),
         show_post(State.post),
    )
```

**Comment by Lendemor** [comment]
I don't think it's the right approach.

Currently we have a the `hydrate_middleware` that actually run the on_load.
We probably need to make some update in that middleware so as to re-trigger the on_load when the route change.

**Comment by masenf** [comment]
That's a very good point. For a non-general solution that just handles the successful load it would probably be simpler to just hook `routeChangeComplete` event, and have _that_ re-call `State.hydrate`, which would re-trigger `on_load`.

Very simple. Nice!
