### ISSUE TITLE
pc.html can't accept state vars 

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#612]
**Describe the bug**

**To Reproduce**
 - Code/Link to Repo:

```python 
import pynecone as pc

class State(pc.State):
   example_html = """
    <div>
        <h1>Pynecone</h1>
        <p>Pynecone is a Python library for creating web apps.</p>
        <p>It is designed to be easy to use and to be able to create complex apps with minimal code.</p>
        <p>It is also designed to be easy to extend and customize.</p>
    </div>
    """

def index():
    return pc.center(
        pc.html(
            State.example_html 
        )
    )

app = pc.App(state=State)
app.add_page(index)
app.compile()
```

**Expected behavior**

Should work be able to take in a state var as input but getting the error below.
```
TypeError: Invalid var passed for prop dangerouslySetInnerHTML, expected type pynecone.var.Var[typing.Dict], got value {'__html': BaseVar(name='example_html', type_=<class 'str'>, state='state', is_local=False, is_string=False)} of type <class 'dict'>.

```
** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 0.1.18
 - OS: Darwin

**Comment by d29107d** [comment]
@Alek99 
I test in the `main` branch, and it is fine.

**Comment by Alek99** [comment]
Ok may have been fixed let me lets and I'll close this.

**Comment by Alek99** [comment]
I'm still getting this error, will put up a fix for it now

**Comment by csears** [comment]
I found a workaround for this bug. Example [here](https://github.com/pynecone-io/pynecone/issues/490#issuecomment-1483851463)

**Comment by jq6l43d1** [comment]
I think this issue needs to be reopened.
