### ISSUE TITLE
Question: Where is Pynecone installed?

### ISSUE THREAD

**Issue by PoshoDev** [pynecone-io/pynecone#621]
Sorry if this is a goofy question to be asked. I'm trying to run a Pynecone app from a separate Python script and I get an error.
```python
subprocess.Popen(". venv/bin/activate", shell=True)
subprocess.Popen("pc run --port 5000", shell=True)
```
```bash
/bin/sh: 1: pc: not found
```
I understand that this is because the shell is unable to find the executable `pc` in the system's search path. So I'm assuming running this process with the full path of `pc` would fix this.
I'm using Linux so my first thought was to use `whereis` and `which` with root privileges, but both return empty results. I checked my `.bashrc` file since some programs (such as *bun* it seems) insert themselves in there upon installation.
I also tried running `pc` directly from Python:
```bash
posho@Posho-Laptop:~$ python3 -m pc
/usr/bin/python3: No module named pc
posho@Posho-Laptop:~$ python3 -m pynecone
/usr/bin/python3: No module named pynecone
```
I obviously checked the [docs](https://pynecone.io/docs/getting-started/installation) too, as well as looking for any setup files in the [repository](https://github.com/pynecone-io/pynecone) for some answers but with no avail.
Pardon me for giving too much context, I just wanted to let you know I _did_ try to look it this all up before coming here to post the question. 😅
If possible, I would also like to know where Pynecone is installed in Mac as well. Thank you for any further advice.
| OS | Ubuntu 22.04.2 LTS |
| :--- | :--- |
| Python | 3.10.6 |
| Pynecone | 0.1.18 |
| bun | 0.5.7 |

**Comment by dev-onejun** [comment]
It is due to the fact that each lines in `subprocess.Popen()` execute each child process separately.

In other words, your commands which activates venv environment and which run pinecone (pc run) runs on a different shell.

So if you want to run like on your purposes, you should run command like below.

``` python
subprocess.Popen('. venv/bin/activate && pc run --port 5000', shell=True)
```

**Comment by dev-onejun** [comment]
As returning to your question, `pynecone` will be located at your `venv` directory if you installed it after activating.

In my opinion, that is why you could not run `python3 -m pc` which `python3` is the python command of system.

If you want to execute as `python3 -m pc`,

``` bash
$ python3 -m pip install -U pynecone-io
```

would works.

**Comment by PoshoDev** [comment]
Oh, that's interesting. Didn't cross my mind to do something as simple as that. 😅
Thank you very much!

**Comment by PoshoDev** [comment]
> It is due to the fact that each lines in `subprocess.Popen()` execute each child process separately.

> ```python
> subprocess.Popen('. venv/bin/activate && pc run --port 5000', shell=True)
> ```
Oh, that's interesting. Didn't cross my mind to do something as simple as that. 😅


> As returning to your question, `pynecone` will be located at your `venv` directory if you installed it after activating.

You're absolutely right.
```bash
posho@Posho-Laptop:~/Repos/Gator$ source venv/bin/activate
(venv) posho@Posho-Laptop:~/Repos/Gator$ whereis pc
pc: /home/posho/Repos/Gator/venv/bin/pc
```

Thank you very much for your advice! 🙂
