### ISSUE TITLE
Ability of put any HTML to App

### ISSUE THREAD

**Issue by FHU-yezi** [pynecone-io/pynecone#65]
As you know, lots of Python plotting libraries support to output the result to HTML. Take PyEcharts for example, just use `your_graph_obj.render_notebook()`, and put the output to App, you got a wonderful graph based on Echarts.

It can let us support more plotting libraries with just a bit work.

**Comment by Alek99** [comment]
Sure I can definitely add a component that lets you insert arbitrary html, pc.html(). I'll try and add this in the next release scheduled for Friday

**Comment by Alek99** [comment]
https://github.com/pynecone-io/pynecone/pull/98
