### ISSUE TITLE
Ensure underscores convert to hyphens for path names

### ISSUE THREAD

**Issue by simonmesmith** [pynecone-io/pynecone#66]
I was running into an issue using a page function that includes an underscore.

For example, if I use this:

```python
def sign_up():
```

Instead of this:

```python
def signup():
```

I'll get this error at /sign_up:

```
Unhandled Runtime Error
Error: Invariant: attempted to hard navigate to the same URL
```

After some exploration, I think it's because of the underscore.

I can fix the problem as follows:

```python
app.add_page(sign_up, path="/sign-up")
```

I'm not sure why this is happening because in `add_page()` you call `utils.format_route(path)`, which should solve this.

If it helps, I'm importing this page as follows:

```python
from pynecone_experiment.pages.sign_up import sign_up
```

**Comment by picklelo** [comment]
That's definitely a bug, I'll look into this - thanks for catching it!

**Comment by simonmesmith** [comment]
Hmm. I'm working on something now with log_in, and it's getting properly converted to log-in it seems. So it's possible that there's something else I did to cause the problem. I'll let you know if I come across it again. It's possible something else caused the problem and this isn't an issue. If so, sorry!

**Comment by picklelo** [comment]
Yeah it seems to be working for me locally. One thing you can do if this happens again is check in the `.web/pages` directory. There should be a single file for each compiled page, with the matching route.

**Comment by simonmesmith** [comment]
Yeah, works. Looks like it may have been a different error. I moved my pages into a /pages subdirectory to make things cleaner, and may have broken something doing that. Sorry for the fire drill.
