### ISSUE TITLE
pc run hang on 'bun install'  for hours!

### ISSUE THREAD

**Issue by CocoaRush** [pynecone-io/pynecone#675]
**Describe the bug**
After command `pc run`, there will be **Starting Pynecone App**, and **Installing frontend packages**, then `bun install v0.5.7 (5929daee)`, that's it, it will keep this line for hours, just wondering that's going on and how could get round it?

**To Reproduce**
follow the instructions on the website:
```
pip install pinecone
pc init
pc run
```

**Expected behavior**
local website can be visited

**Screenshots**
<img width="910" alt="image" src="https://user-images.githubusercontent.com/2907559/224916409-d51e569f-48f6-4439-be37-452a8f1da941.png">

** Specifics (please complete the following information):**
 - Python Version: 3.7.9
 - Pynecone Version: 0.1.18
 - OS: macOS 12.6.2
 - Browser (Optional):

**Comment by Alek99** [comment]
Hi can you downgrade to v0.5.5 I think there is a problem in the latest version of bun

**Comment by Alek99** [comment]
I think this should solve it

**Comment by CocoaRush** [comment]
@Alek99 thanks, I will give it a try. But how can I downgrade bun, or how can I install bun for a specific version?

**Comment by FHU-yezi** [comment]
> @Alek99 thanks, I will give it a try. But how can I downgrade bun, or how can I install bun for a specific version? 

You can try to uninstall it and install again with pc run, we currectly use the specific version of bun in install script.

**Comment by Alek99** [comment]
> @Alek99 thanks, I will give it a try. But how can I downgrade bun, or how can I install bun for a specific version?

curl -fsSL https://bun.sh/install | bash -s -- bun-v0.5.5

**Comment by Electroid** [comment]
Hi, I work at Bun. Sorry you're running into this, we're working on a fix. https://github.com/oven-sh/bun/issues/2392

**Comment by locriacyber** [comment]
How do I use `pnpm` instead?

**Comment by Alek99** [comment]
> Hi, I work at Bun. Sorry you're running into this, we're going to investigate to see if this is an issue with Bun. [oven-sh/bun#2392](https://github.com/oven-sh/bun/issues/2392)

Awesome thank you!

**Comment by Alek99** [comment]
We may need to add a special warning in Pynecone if bun version was causing this. I'll add this
