### ISSUE TITLE
`www.pynecone.io` doesn't work

### ISSUE THREAD

**Issue by tushar-deepsource** [pynecone-io/pynecone#693]
**Describe the bug**
`pynecone.io` loads the website, but `www.pynecode.io` does not.

It looks like you're missing a `www` CNAME record in your DNS config.

**Screenshots**
![image](https://user-images.githubusercontent.com/86737547/225559117-5bd0df57-bbba-452c-b596-0e765ee06a8b.png)

![image](https://user-images.githubusercontent.com/86737547/225559078-f775bf5c-5d86-4871-a0a7-acbe07e9b14e.png)

**Comment by Alek99** [comment]
Got it thanks for pointing this out.
