### ISSUE TITLE
pc.data should be able to take in state var component code.

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#696]
**Describe the bug**

pc.data can't take in state vars in the render code.

**To Reproduce**
 - Code/Link to Repo:

See screenshot below.

**Expected behavior**

Should work with state vars in the ui.

**Screenshots**
<img width="790" alt="Screen Shot 2023-03-16 at 9 54 00 AM" src="https://user-images.githubusercontent.com/38776361/225694367-a6fdeb9f-f3fb-4127-9075-03bc79a07c04.png">

**Comment by HoughIO** [comment]
@Alek99  what's the workaround for this you've been using? I'm finding it hard to build out graphs.

**Comment by Alek99** [comment]
> @Alek99 what's the workaround for this you've been using? I'm finding it hard to build out graphs.

As a solution to this you can just make one computed var that returns a pc.data
