### ISSUE TITLE
"ModuleNotFoundError: No module named '_sqlite3'" Running "pc init" from Pynecone Installed in Virtual Environment

### ISSUE THREAD

**Issue by hebozhe** [pynecone-io/pynecone#704]
**Describe the bug**
I installed Pynecone into a virtual environment to try it out. I have the relevant sqlite3 package installed globally and was able to pip-install it into my python3.11 distro. However, when I run the `pc init` command, I get the following error:

>ModuleNotFoundError: No module named '_sqlite3'

**To Reproduce**
From my Ubuntu terminal:
1. `cd /way/to/project/dir`
2. `python3.11 -m venv project_venv`
3. `project_venv/bin/activate`
4. `pip install pynecone`
5. `pc init`

**Expected behavior**
>You should see your app running at http://localhost:3000/.

**Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 0.1.20
 - OS: Linux
 
**Additional context**
Do I need to install Pynecone globally into my Python 3.11 pip repository? I would really prefer not to have to do that, since I am routinely creating virtual environments for other projects.

**Comment by hebozhe** [comment]
This solved it. Looks like there's an issue using the PPA to install Python without having the required libraries installed beforehand for the build. It's covered [at this StackOverflow link](https://stackoverflow.com/questions/39907475/cannot-import-sqlite3-in-python3) .

**Comment by Alek99** [comment]
Ok nice. Sorry for the delayed response was busy last week.

Will mark as resolved.
