### ISSUE TITLE
Can't connect to backend via wss

### ISSUE THREAD

**Issue by simicvm** [pynecone-io/pynecone#711]
**Description**
Web app loads properly, but it is unable to communicate with backend when running in production mode and using self hosting (AWS EC2). Web UI has an input field where users should input some text (url). However, it is not possible to input any text because UI can't communicate with backend.

App works fine when running on the local machine. 

Error I get in browser console:
```
WebSocket connection to 'wss://shoki.app:8000/event/?EIO=4&transport=websocket' failed: An SSL error has occurred and a secure connection to the server cannot be made.
```

`pcconfig.py` file I use:
```python
config = pc.Config(
    app_name="youtube_scribe",
    api_url="https://shoki.app:8000",
    db_url="sqlite:///pynecone.db",
    env=pc.Env.PROD,
)
```

**Expected behavior**
User inputs the URL in the input field and press the button. App takes the URL, sends to backend, calls some API, obtain results, and display them in web UI.

** Specifics (please complete the following information):**
 - Python Version: 3.10.6
 - Pynecone Version: 0.1.20
 - OS: Ubuntu 22.04.1 LTS
 - Browser (Optional): Chrome, Safari
 
**Additional context**
I tried many different versions of `api_url` and `port` in `pyconfig.py` but nothing seems to work, and certain configurations have different error types.

When public url is on `http` (instead of `https`) the app also works fine.

**Comment by simicvm** [comment]
I found similar issues, but didn't manage to solve my problem: https://github.com/pynecone-io/pynecone/issues/698 https://github.com/pynecone-io/pynecone/issues/441 https://github.com/pynecone-io/pynecone/issues/403

**Comment by simicvm** [comment]
solved it. The issue was in two places, `pcconfig` and `nginx` config.

in `pcconfig` I incorrectly set `api_url` with the port number e.g., `api_url="https://some.app:8000"` instead or `api_url="https://some.app"`

and in `nginx` I had to add SSL certificates, as well as have two different paths:
```
location / {
    proxy_pass http://localhost:3000;
    ...
}
```
and
```
location /event/ {
    proxy_pass http://localhost:8000;
    ...
}

**Comment by Alek99** [comment]
This for posting the solution @simicvm really helpful!

**Comment by nguyenhoanganh2002** [comment]
@simicvm where are `pcconfig` and `nginx` config locate?

**Comment by picklelo** [comment]
@nguyenhoanganh2002 `pcconfig` is now the `rxconfig.py` file. The `nginx` config isn't in Reflex, that would be dependent on how you're hosting your app.

**Comment by DUBSON0** [comment]
Hi, I've run into a similar issue using nginx. I attempted the remedy above to no avail.

This is the error displayed on the app page: 
Check if server is reachable at ws://worcester3d.com:8000/_event

I am having trouble understanding what is supposed to be happening topographically but the notion that I am working off of is as follows:

Client <--> nginx <--> Port 3000 Frontend
                                ^--> Port 8000 Backend

I upgraded both port 3000 and 8000 to enable ws [(rx docs)](https://reflex.dev/docs/hosting/self-hosting/#production-mode) but now I am confused about where '/event' is located. Should nginx be installed in the same virtual environment as reflex? 

The config for 8000:

`map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
}
server {
    location /_event/ {
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://192.168.1.201:8000;
}
}
`
And the config for 3000:
`map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
}


server {
    listen 80;
    listen [::]:80;

    server_name worcester3d.com www.worcester3d.com;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_pass http://192.168.1.201:3000;
}
}`

**Comment by djeinstine** [comment]
`Client <--> nginx <--> Port 3000 Frontend<--> Port 8000 Backend`
 That was my first thought when I first started developing JS front ends. But that's not the case. Both front end and back end communicate with the reverse proxy and need their own SSLs.

**Comment by Decrescent398** [comment]
@picklelo What do I do if I'm using caddy?

` {
    admin unix//home/(username)/caddy-admin.sock
}

http://(website) {
    bind unix/.(website).webserver.sock|777

    # Handle Reflex/WebSocket connections
    handle /_event* {
        reverse_proxy localhost:5055 {
            header_up Connection {>Connection}
            header_up Upgrade {>Upgrade}
        }
    }

    @frontend {
        not {
            path /api/*
            path /_event*
        }
    }
    handle @frontend {
        reverse_proxy localhost:5055
    }

    handle_path /api/* {
        reverse_proxy localhost:5056
    }
}`
