### ISSUE TITLE
error when accessing external to server - Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by biobrad** [pynecone-io/pynecone#714]
**Describe the bug**

This works fine when using pc run and accessing local host in dev mode, however i have tried to deploy to two separate servers and i get this same issue.

(I also get the issue when using pc run without the --env prod and accessing the server local host)

When attempting to self-host, page loads, but with no functionality.
using the command pc run --env prod

Console gives the folllowing error:

```
(30) Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at index-5219258fe035328f.js:1:1921
    at main-0676cfe1c4ae880c.js:1:101925
    at Object.next (main-0676cfe1c4ae880c.js:1:102030)
    at n (613-8edbbe55388aab0d.js:1:78913)
    at a (613-8edbbe55388aab0d.js:1:79116)
    at 613-8edbbe55388aab0d.js:1:79175
    at new Promise (<anonymous>)
    at 613-8edbbe55388aab0d.js:1:79056
    at index-5219258fe035328f.js:1:2220
    at index-5219258fe035328f.js:1:3312
```

Upon clicking on the error:

```
   }(), j = function() {
            var e = (0,
            s.Z)((function(e, t, n, r, s, o, i, a) {
                var u;
                return (0,
                c.__generator)(this, (function(c) {
                    return u = new URL(i),                <<<<<<<< errored line
                    e.current = (0,
                    p.ZP)(i, {
                        path: u.pathname,
```

**To Reproduce**
 - Code/Link to Repo: Link below to repo with main configuration file and also pcconfig.py file.
 -  https://github.com/biobrad/SLA_Matrix
 

**Expected behavior**

I expected the page to work the same as it does when using dev and localhost

**Screenshots**
<img width="680" alt="image" src="https://user-images.githubusercontent.com/55652506/226519186-34c5be7d-d13d-40c5-9737-2aaa14c36d27.png">
<img width="921" alt="image" src="https://user-images.githubusercontent.com/55652506/226519316-7255b881-5822-424d-919e-d0fc66ac630b.png">

** Specifics (please complete the following information):**
 - Python Version: 3.10
 - Pynecone Version: 0.1.19
 - OS: CatOS 8.5 and Ubuntu 22.04
 - Browser (Optional):
 -chrome or firefox
 
**Additional context**

Just wanted to say thank you for building pynecone. It is really awesome to be able to get some nodejs functionality into a page with python!

**Comment by biobrad** [comment]
i just tried with on of the example apps, getting the same error:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/55652506/226564840-355dbc9b-b8c2-4259-b9f5-402a14be9252.png">

**Comment by Alek99** [comment]
Got we will try and recreate and get back to you on this. Is this still erroring in the latest v0.1.20 release?

**Comment by biobrad** [comment]
Hi Alek,
I think so.
Will check again.
I really hope it isn't something from my side.
I have a less than rudimentary understanding of JS so I apologise for not
being able to troubleshoot myself. (I did try though!)
Cheers
Brad

**Comment by Alek99** [comment]
> Hi Alek, I think so. Will check again. I really hope it isn't something from my side. I have a less than rudimentary understanding of JS so I apologise for not being able to troubleshoot myself. (I did try though!) Cheers Brad
> […](#)

Ok we will try and recreate this error tomorrow, haven't seen this before but we'll get to the bottom of it. 

The UI of your app looks really good! Excited to see it once it's finished!

**Comment by janzheng** [comment]
Hmm I'm getting this problem running a local Docker container. It's probably some environment error related to my Dockerfile?

```
FROM python:3.11-slim as base

RUN adduser --disabled-password pynecone


FROM base as build

WORKDIR /thirdtry
ENV VIRTUAL_ENV=/thirdtry/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY . .

RUN pip install wheel \
    && pip install -r requirements.txt


FROM base as runtime

RUN apt-get update && apt-get install -y \
    curl \
    && curl -fsSL https://deb.nodesource.com/setup_19.x | bash - \
    && apt-get update && apt-get install -y \
    nodejs \
    unzip \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g n
RUN n latest
RUN npm install -g npm@latest
RUN npm install -g yarn

ENV PATH="/thirdtry/venv/bin:$PATH"


FROM runtime as init

WORKDIR /thirdtry
ENV BUN_INSTALL="/thirdtry/.bun"
COPY --from=build /thirdtry/ /thirdtry/
RUN pc init

RUN yarn install --update-checksums --cwd /thirdtry/.web
RUN yarn add next @emotion/react @chakra-ui/react focus-visible


FROM runtime

COPY --chown=pynecone --from=init /thirdtry/ /thirdtry/
USER pynecone
WORKDIR /thirdtry

CMD ["pc","run" , "--env", "prod"]

EXPOSE 3000
EXPOSE 8000
```
