### ISSUE TITLE
Websockets randomly close

### ISSUE THREAD

**Issue by jshahbazi** [pynecone-io/pynecone#716]
When making REST calls and waiting for a response, after the response is received, the websocket connection will close randomly, though consistently.

```
DEBUG:    < CLOSE 1005 (no status code [internal]) [0 bytes]
DEBUG:    = connection is CLOSING
DEBUG:    > CLOSE 1005 (no status code [internal]) [0 bytes]
DEBUG:    x half-closing TCP connection
DEBUG:    = connection is CLOSED
```

** Specifics (please complete the following information):**
 - Python Version: 3.9, 3.10
 - Pynecone Version: v0.1.20
 - OS: macOS, Ubuntu
 - Browser (Optional): Safari, Chrome
 
**Additional context**

**Comment by picklelo** [comment]
We increased the connection timeout so hopefully this issue doesn't happen anymore. Please reopen if anyone runs into this.
