### ISSUE TITLE
Fast Refresh fails half  the time

### ISSUE THREAD

**Issue by axljones** [pynecone-io/pynecone#721]
**Describe the bug**
Fast refresh doesn't seem to work very well. Either nothing happens when i modify my code or a fest refresh error appears

**To Reproduce**

1. pc run >> works okay
2. modify code
3. following error appears "warn  - Fast Refresh had to perform a full reload. Read more: https://nextjs.org                                                                                                                                                                             /docs/basic-features/fast-refresh#how-it-works"

**Expected behavior**
Dev to be running

**Screenshots**
![image](https://user-images.githubusercontent.com/24891578/227567743-e5dd67f1-0aee-4995-9c31-cb9e37b250fd.png)

** Specifics (please complete the following information):**
 - Python Version: 3.9
 - Pynecone Version: latest
 - OS: debian (wsl2)

**Additional context**

**Comment by Alek99** [comment]
Is this issue happening for anyone else?

**Comment by IanDanielM** [comment]
its happening to me too,, making development really slow

**Comment by ElijahAhianyo** [comment]
This is not a pynecone related bug. There are limitations and incompatibilities between the WSL file system and the Windows file system which prevents the hot reload feature from working correctly. As a workaround, you should move your project/files to the WSL file system when using WSL. This should work just fine

**Comment by axljones** [comment]
> This is not a pynecone related bug. There are limitations and incompatibilities between the WSL file system and the Windows file system which prevents the hot reload feature from working correctly. As a workaround, you should move your project/files to the WSL file system when using WSL. This should work just fine

You were 100% correct. Not only did it fix my fast refresh issues but the dev now starts blazingly fast in seconds where it would take a few minutes to run before.

I don't know if this should be included in the readme or doc. It's not really related to pynecone but i feel like many other people have the same issue.

**Comment by FHU-yezi** [comment]
Yes, due to the special way to access Wndows files in WSL, the IO between Windows and Linux is vary slow.

**Comment by ElijahAhianyo** [comment]
closing this issue now

**Comment by marc-odp** [comment]
I am happy that I found that post because I was experimenting exactly the same problems. Reflex was very slow and refresh was not happening.
