### ISSUE TITLE
Local build fails in poetry < 1.4.0

### ISSUE THREAD

**Issue by kasun** [pynecone-io/pynecone#731]
Currently when trying to build pynecone locally with poetry version < 1.4.0 it fails for two different reasons.

1. `group` notation was introduced to the pyproject.toml file as part of #619 but poetry doesn't have `group` support prior to version < 1.2.0

2. Building with poetry version <= 1.30 fails because of some incompatibility with following error.

```
The lock file is not compatible with the current version of Poetry.
Upgrade Poetry to be able to read the lock file or, alternatively, regenerate the lock file with the `poetry lock` command.
```

Shall we update documentation mentioning poetry version >= 1.4.0 is needed to build the project locally? Happy to submit a PR if this is agreed.

**Comment by ElijahAhianyo** [comment]
Hi @kasun, thanks for this. Sure, You can go ahead and do just that
