### ISSUE TITLE
Var List Index Change, UI Not Being Updated

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#737]
**Describe the bug**

Creating this ticket to not forget about this issue.

We need to investigate if editing an element in a list marks it as dirty so the frontend updates.
**To Reproduce**
 - Code/Link to Repo:
<img width="1100" alt="Screen Shot 2023-03-27 at 11 38 10 PM" src="https://user-images.githubusercontent.com/38776361/228149547-d00da376-52c9-407b-b6da-3241b4f0a1ca.png">

**Expected behavior**

Should update the ui with the edited list.

**Comment by picklelo** [comment]
This should work in the latest version (v0.1.21)
