### ISSUE TITLE
replace `requests` with `httpx`

### ISSUE THREAD

**Issue by FHU-yezi** [pynecone-io/pynecone#74]
`httpx` is a requests-like Python network package. It can be a drop-in replacement of `requests`.

[HTTPX GitHub Repo](https://github.com/encode/httpx/)

[Documentation](https://www.python-httpx.org/)

Just search for any use of requests and I only found the command line tool `pc` use it, for a subcommand `deploy` which is unused now, so feel free to leave it there until we release the deploy feature.

**Comment by picklelo** [comment]
Thanks, we will update this.
