### ISSUE TITLE
Function looks perfect from localhost, but not from server

### ISSUE THREAD

**Issue by johnvonneumann36** [pynecone-io/pynecone#747]
Here is the problem:
When I set a switch to control if a component is disabled or not, it works fine via localhost but malfunctions when I visit it from another device.

```
# type: ignore
from pcconfig import config
import pynecone as pc

docs_url = "https://pynecone.io/docs/getting-started/introduction"
filename = f"{config.app_name}/{config.app_name}.py"

class State(pc.State):
    tag: bool = True
    def set_tag(self, tag):
        self.tag = not tag


def index() -> pc.Component:
    return pc.box(
        pc.vstack(
            pc.switch("If Tag", padding_top="2%", on_change=State.set_tag, ),
            pc.select(
                ['lt', 'le', 'eq', 'ge', 'gt'], 
                default_value='ge',
                padding_top="2%", 
                is_disabled=State.tag,
            ),
        ),
    )

# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index)
app.compile()
```

Expected behavior:
I think this feature should behave the same when accessing the site in different ways.

** Specifics (please complete the following information):**
 - Python Version: 3.7.4
 - Pynecone Version: 0.1.18
 - OS: Windows Server 2019
 - Browser (Optional): Chrome Local/Remote
 
**Additional context**

**Comment by johnvonneumann36** [comment]
I'm wondering if this is caused by websocket when the network is not perfect.

**Comment by Lendemor** [comment]
Page will be unresponsive if the websocket can't connect to the backend.
Usually checking the api_url is how it can be solved.
