### ISSUE TITLE
Improving chat UI performance and user experience with new event type

### ISSUE THREAD

**Issue by kyb3r** [pynecone-io/pynecone#753]
While developing a chat UI, I've encountered performance issues when typing into a text box that has its value property bound to a variable. Similarly, using the `on_keydown` event to check if the "Enter" key was pressed and then executing the message sending code also results in poor performance.

Our current workaround is to utilize the `on_unblur` event for saving the text to the state and clicking a button to send the message. However, this approach isn't very user-friendly.

To address these issues, I propose the introduction of a new event type, such as `on_enter`, that triggers upon pressing the "Enter" key. Additionally, we need a method to clear the text box once the "Enter" key is pressed, since the only existing method involves binding the value property. This should improve both performance and user experience in the chat UI.

**Comment by picklelo** [comment]
I'm working on a `pc.form` component that should solve this use case.

**Comment by picklelo** [comment]
This should be resolved by #923 which adds a `pc.form` component with an `on_submit` event trigger that is called when the user presses enter.

Marking this as a duplicate -aiming to get that in by the next release.
