### ISSUE TITLE
Audio Component?

### ISSUE THREAD

**Issue by dakl** [pynecone-io/pynecone#77]
Does there exist a component like similar to Streamlit [audio](https://docs.streamlit.io/library/api-reference/media/st.audio)? Or plans to implement? Would be lovely :)

**Comment by FHU-yezi** [comment]
#26

**Comment by Alek99** [comment]
Thanks for the suggestion, this is something we can add. Agree with @FHU-yezi  see that discussion for component requests.

**Comment by maylad31** [comment]
yeah that would be a great addition
