### ISSUE TITLE
Update `pc run` backend/frontend only flags

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#786]
Currently the flags are `--no-frontend` and `--no-backend`, but we should change it to match the `pc export` flags - `--backend-only` and `--frontend-only`

**Comment by milochen0418** [comment]
Run backend with port 8000
```
pc run --backend-only --backend-port=8000
```

Run frontend with port 3030
```
 pc run --frontend-only --port=3030
 ```
