### ISSUE TITLE
Error: Pynecone requires bun to be installed

### ISSUE THREAD

**Issue by Chitra999** [pynecone-io/pynecone#793]
Dear Pynecone team,

I'm trying to use Pynecone on my Windows 10 machine and I'm running into an issue with the 'pc init' command. I've installed Pynecone using pip and it seems to have installed correctly, but when I try to run 'pc init', I get a 'FileNotFoundError' with the message "Pynecone requires bun to be installed."

I've checked and it seems like I do have bun installed already, as I installed it using pip before installing Pynecone. I'm using Python 3.11 and the latest version of Pynecone (0.1.0) and bun (0.0.8). It should have detected the bun package and pc init command would have run successfully.

Could you please advise on what I might be doing wrong and how I can resolve this issue? I'm not very experienced with Python so any help would be greatly appreciated.

Thank you,
Chitra999.

[**Screenshots**]
![image](https://user-images.githubusercontent.com/67793217/230779237-619aa46b-596a-411b-a2ac-5492dcd40117.png)
![image](https://user-images.githubusercontent.com/67793217/230779268-1ede0060-3eda-421c-9ee6-0d3e0008f454.png)

 - Python Version:3.10
 - Pynecone Version:0.1.0

**Comment by juten84** [comment]
I had the same problem, this seems to be an issue with the last version of pynecone. I change to version 0.1.21 and it works well

**Comment by Alek99** [comment]
Yeah that pynecone version is very old try upgrading to the latest release

**Comment by sheldonchiu** [comment]
https://github.com/pynecone-io/pynecone/issues/783
PR768 is the cause of this issue, need to fix install_bun()

**Comment by picklelo** [comment]
Thanks for catching, just put up a PR #796 to fix this - we will do a release ASAP
