### ISSUE TITLE
prod mode doesn't work right away

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#814]
If you try to `pc run --env prod` directly after `pc init` you get this error

```
$ next build && next export -o _static
/bin/bash: next: command not found
error: script "export" exited with code 127
$ next start
/bin/bash: next: command not found
error: script "prod" exited with code 127
```

**Comment by r0b2g1t** [comment]
I know that pynecone use ```bun``` for build/run/export/... under the hood. Do you tried to run it via ```bun``` without the ```pc``` command?

**Comment by jefflinwood** [comment]
I'm running into this problem when doing a `pc export` in a `Dockerfile` - I do get the same exact error if I call `bun run export` instead.

**Comment by LouisFaure** [comment]
Also found that issue while making my own docker containers, the solution I found is to run the following before `pc init` and `pc run --env prod`:

```bash
python3 -c 'from pynecone.utils.prerequisites import install_frontend_packages as f; f(".web")'
```

`install_frontend_packages` is likely only called when running in dev environment, so running in prod right away miss the important step of installing all dependencies.

**Comment by r0b2g1t** [comment]
I have tested this week many things with the prod execution and the reason why for example ```next``` was not found is that the bun download of the dependencies only run when you run "pc run" which belongs to the dev. That is also the reason why the container image isn't running. which I will fix.

An idea is to introduce a pc parameter to install the dependencies. Like:
```
pc --install-dependencies
or
pc --bun-install
or
...
```

**Comment by batmaidTymon** [comment]
+1
