### ISSUE TITLE
error parsing lockfile

### ISSUE THREAD

**Issue by NanoscaleSimulations** [pynecone-io/pynecone#826]
**Describe the bug**
Every time i run `pc run` I get a lockfile error and it starts to install some packages but end up saying:
`error parsing lockfile: Lockfile is missing resolution data
ignoring lockfile`

It still manages to start the server, but does not send changes to the server.

**To Reproduce**
conda activate pynecone
pc init
pc run

**Expected behavior**
The server should be running live.

**Screenshots**
[https://nanoscalesimulations.com/Gallery/Screenshot%202023-04-15%20123251.png](url)

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 0.1.22
 - OS: Ubuntu
 - bun install: v0.5.9 
 
**Additional context**
I am running it on wsl (Ubuntu) and within a conda environment.

**Comment by ElijahAhianyo** [comment]
the lockfile error is related to the bun package. However, this should work normally. The server not receiving changes(hot reload) is as a result of incompatibilities between the WSL file system and Windows file system. Consider moving your project to the WSL file system and that should work just fine. Check this [issue](https://github.com/pynecone-io/pynecone/issues/721) for more.
My best guess is, your app should run fine with the bun error. However, if you still have any bun related issues, I'd recommend downgrading your bun version to `v0.5.8` or `v0.5.5`
