### ISSUE TITLE
Installing npm packages inside a docker container fails with bun

### ISSUE THREAD

**Issue by r0b2g1t** [pynecone-io/pynecone#857]
**Describe the bug**
If you create a Docker image from the Dockerfile, the packages will not installed and bun creates error for every package. This bug is already reported to bun ([1590](https://github.com/oven-sh/bun/issues/1590)). The issue can reproduced only in non interactive environment.

```bun install v0.5.5 (242dcea2)
  🚚 internmap... Integrity check failed for tarball: internmap
  🚚 internmap... error: IntegrityCheckFailed extracting tarball for internmap  🚚 d3-ease... Integrity check failed for tarball: d3-ease
  🚚 d3-ease... error: IntegrityCheckFailed extracting tarball for d3-ease  🚚 @types/d3-timer... Integrity check failed for tarball: @types/d3-timer
  🚚 @types/d3-timer... error: IntegrityCheckFailed extracting tarball for @types/d3-timer  🚚 @types/d3-path... Integrity check failed for tarball: @types/d3-path
```

**To Reproduce**
Create a Pynecone docker image.

**Expected behavior**
The pynecone app will start without error like next not found.

 
**Additional context**

**Comment by Alek99** [comment]
https://github.com/pynecone-io/pynecone/pull/860 closes this issue. Thanks @r0b2g1t !
