### ISSUE TITLE
Make event handler / lambda args optional

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#862]
Currently the following code doesn't work:

```python
    pc.select(
        SpreadsheetState.worksheets,
        placeholder="Select A Worksheet",
        on_change=[
            SpreadsheetState.set_selected_worksheet,
            SpreadsheetState.show_columns,
        ],
    ),
```

because the `on_change` for select takes in a value. Currently you have to do this:

```python
lambda _: SpreadsheetState.show_columns()
```

We should make both the lambda arg and the event handler arg optional

**Comment by Lendemor** [comment]
If we have the following select component: 
```
pc.select(
    ["hello", "world"], 
    on_change=[St.ev1, St.ev2]
)
```

We could have either:
1. All the EventHandlers from the chain receive the arg from on_change (ev1 & ev2 need correct signature)
```
def ev1(self, arg):
    ...

def ev2(self, arg):
    ...
```

2. Only the first EventHandler ev1 receive the arg from on_change (ev1 need correct signature, ev2 doesn't expect anything)
```
def ev1(self, arg):
    ...

def ev2(self):
    ...
```

3. Optional args => ev1 and/or ev2 are allowed to have incorrect signature, but only if they expect less args than returned by the event.
```
def ev1(self):
    ...

def ev2(self):
    ...
```

Option1 is the current state of things, and admittedly not what we want, so not considering it.

Option2 work with the first example provided, but doesn't allow as much flexibility as Option3.

Option3 has the risk of not raising any error when users provide an EventHandler with incorrect signature.
We could mitigate the risk if the optional args are only applicable within an EventChain?

**Comment by FHU-yezi** [comment]
I think we need to stay tight on the number of parameters, otherwise we may have maintenance problems when the code base becomes larger, because we will dynamically decide the number of parameters to pass in at runtime, and if developers don't pay attention to the documentation, they may introduce code that is difficult to understand.
