### ISSUE TITLE
Long-running events do not propagate state updates to the frontend

### ISSUE THREAD

**Issue by mengcius** [pynecone-io/pynecone#865]
After clicking pc.button, if the inner program runs for a long time (eg.2min), you won't be able to actually update the State class properties (eg.self.image_made =True). Even if the internal program ends and the printed self.image_made has become True, it is still not possible to determine the True self.image_made==True(eg. the combination pc.cond will never trigger), Unless the page is refrested.

**Comment by kbrgl** [comment]
Thanks for reporting this. Trying to reproduce.

**Comment by mengcius** [comment]
Thanks for your reply, you can use the following code to reproduce.

`
"""Welcome to Pynecone! This file outlines the steps to create a basic app."""
import pynecone as pc
# import openai
from random import choice
import time

# openai.api_key = "YOUR_API_KEY"
img_exa = [
    'https://replicate.delivery/pbxt/qcrZfAJuW71mNyiN9MZh65WW8LkTKLQHAPtasZdE0RMXxZLIA/out-0.png',
]

class State(pc.State):
    """The app state."""

    prompt = ""
    image_url = ""
    image_processing = False
    image_made = False

    def process_image(self):
        """Set the image processing flag to true and indicate that the image has not been made yet."""
        self.image_made = False
        self.image_processing = True

    def get_image(self):
        """Get the image from the prompt."""
        try:
            # response = openai.Image.create(prompt=self.prompt, n=1, size="1024x1024")
            # self.image_url = response["data"][0]["url"]
            time.sleep(120)
            self.image_url = choice(img_exa)
            # Set the image processing flag to false and indicate that the image has been made.
            self.image_processing = False
            self.image_made = True
            print('self.image_made', self.image_made)
        except:
            self.image_processing = False
            return pc.window_alert("Error with OpenAI Execution.")


def index():
    return pc.center(
        pc.vstack(
            pc.heading("DALL-E", font_size="1.5em"),
            pc.input(placeholder="Enter a prompt..", on_blur=State.set_prompt),
            pc.button(
                "Generate Image",
                on_click=[State.process_image, State.get_image],
                width="100%",
            ),
            pc.divider(),
            pc.cond(
                State.image_processing,
                pc.circular_progress(is_indeterminate=True),
                pc.cond(
                    State.image_made,
                    pc.image(
                        src=State.image_url,
                        height="25em",
                        width="25em",
                    ),
                ),
            ),
            bg="white",
            padding="2em",
            shadow="lg",
            border_radius="lg",
        ),
        width="100%",
        height="100vh",
        background="radial-gradient(circle at 22% 11%,rgba(62, 180, 137,.20),hsla(0,0%,100%,0) 19%),radial-gradient(circle at 82% 25%,rgba(33,150,243,.18),hsla(0,0%,100%,0) 35%),radial-gradient(circle at 25% 61%,rgba(250, 128, 114, .28),hsla(0,0%,100%,0) 55%)",
    )


# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index, title="Pynecone:DALL-E")
app.compile()
`

**Comment by mengcius** [comment]
@kbrgl Thanks for your reply, you can use the following code to reproduce.

```
import pynecone as pc
# import openai
from random import choice
import time

# openai.api_key = "YOUR_API_KEY"
img_exa = [
    'https://replicate.delivery/pbxt/qcrZfAJuW71mNyiN9MZh65WW8LkTKLQHAPtasZdE0RMXxZLIA/out-0.png',
]

class State(pc.State):
    """The app state."""

    prompt = ""
    image_url = ""
    image_processing = False
    image_made = False

    def process_image(self):
        """Set the image processing flag to true and indicate that the image has not been made yet."""
        self.image_made = False
        self.image_processing = True

    def get_image(self):
        """Get the image from the prompt."""
        try:
            # response = openai.Image.create(prompt=self.prompt, n=1, size="1024x1024")
            # self.image_url = response["data"][0]["url"]
            time.sleep(120)
            self.image_url = choice(img_exa)
            # Set the image processing flag to false and indicate that the image has been made.
            self.image_processing = False
            self.image_made = True
            print('self.image_made', self.image_made)
        except:
            self.image_processing = False
            return pc.window_alert("Error with OpenAI Execution.")


def index():
    return pc.center(
        pc.vstack(
            pc.heading("DALL-E", font_size="1.5em"),
            pc.input(placeholder="Enter a prompt..", on_blur=State.set_prompt),
            pc.button(
                "Generate Image",
                on_click=[State.process_image, State.get_image],
                width="100%",
            ),
            pc.divider(),
            pc.cond(
                State.image_processing,
                pc.circular_progress(is_indeterminate=True),
                pc.cond(
                    State.image_made,
                    pc.image(
                        src=State.image_url,
                        height="25em",
                        width="25em",
                    ),
                ),
            ),
            bg="white",
            padding="2em",
            shadow="lg",
            border_radius="lg",
        ),
        width="100%",
        height="100vh",
        background="radial-gradient(circle at 22% 11%,rgba(62, 180, 137,.20),hsla(0,0%,100%,0) 19%),radial-gradient(circle at 82% 25%,rgba(33,150,243,.18),hsla(0,0%,100%,0) 35%),radial-gradient(circle at 25% 61%,rgba(250, 128, 114, .28),hsla(0,0%,100%,0) 55%)",
    )


# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index, title="Pynecone:DALL-E")
app.compile()
```

**Comment by kbrgl** [comment]
I am able to reproduce this issue. Here's a minimal reproduction on main:

```python
import time

import pynecone as pc
from pynecone import el


class State(pc.State):
    """The app state."""

    ready: bool = False

    def on_click(self):
        time.sleep(30)
        self.ready = not self.ready


def index():
    return pc.center(
        pc.vstack(
            pc.cond(State.ready, el.h1("Ready"), el.h1("Not ready")),
            pc.button("Click me", on_click=State.on_click),
        ),
        padding_top="10%",
    )


# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index)
app.compile()
```

30 seconds is roughly the minimum time at which state updates are no longer propagated to the frontend. A few observations:

1. The state update does take place on the backend, because if you refresh the page it is correctly reflected.
2. A new WebSocket is established after the event fires on the backend (see image from Network Inspector below). But this new WebSocket connection does not have a message with the event.

<img width="761" alt="Screenshot 2023-04-28 at 2 28 55 AM" src="https://user-images.githubusercontent.com/13417496/235110844-3038ca59-14ea-4926-aaaf-29d9a212d4b2.png">

**Comment by Alek99** [comment]
That's a good idea for the band aid fix we can do a more in depth fix later, but we can implement this for the next release.

**Comment by charliewei0716** [comment]
Really need this feature, hope to see it soon
