### ISSUE TITLE
Eventhanders calling other other eventhandlers with args

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#876]
Event handlers should be able to call other event handlers with arguments. I think the best way would be todo this with a lambda similar to how its done in our ui elements.

```python
class State(pc.State):
    """The app state."""
    self.option: str = "DFS"

    def bfs(self, arg1, arg2):
       ...

    def dfs(self, arg1, arg2):
       ...

    def run(self):
            """Run the selected algorithm.""
            if self.option == "DFS":
                return lambda _: self.dfs(arg1, arg2)
            elif self.option == "BFS":
                return   lambda _: self.bfs(arg1, arg2)
```
Open to other suggestions.

**Comment by kasun** [comment]
How hard is it to support calling the method directly?

**Comment by picklelo** [comment]
When we do `self.bfs` we are referring to the function, but if we do `State.bfs` it should refer to the event handler itself. Maybe an alternative is that when returning, you should always use the class property, for example:

```python
def run(self):
            """Run the selected algorithm.""
            if self.option == "DFS":
                return State.dfs(arg1, arg2)
            elif self.option == "BFS":
                return State.bfs(arg1, arg2)
```

**Comment by picklelo** [comment]
Added this to the latest docs - will be available in the next website release.
