### ISSUE TITLE
pc init says "Skipping bun installation on Windows" on windows OS.

### ISSUE THREAD

**Issue by automatethem** [pynecone-io/pynecone#879]
**Describe the bug**
pc init says "Skipping bun installation on Windows" and no initial files are generated on windows OS.

**To Reproduce**
 - Code/Link to Repo:
attached screen capture

**Expected behavior**
pc init should generate initial files.

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.10.9
 - Pynecone Version: v0.1.26
 - OS:  Windows 10 Pro
 - Browser (Optional): Chrome

**Additional context**
![cap](https://user-images.githubusercontent.com/108699325/234519881-dfe67f2e-bcc6-4149-bcbe-dcbf9f000b82.PNG)

Thanks

**Comment by HellAmbro** [comment]
It's correct. In windows` pynecone` uses `npm`.
https://github.com/pynecone-io/pynecone/blob/15485f07167e52e6848b8bca58a6a1cb7b8b38a7/pynecone/utils/prerequisites.py#L81
Instead you should run `pc init` before `pc run`

**Comment by automatethem** [comment]
https://github.com/pynecone-io/pynecone/blob/main/pynecone/utils/prerequisites.py#L234

    # Bun is not supported on Windows.
    if platform.system() == "Windows":
        console.log("Skipping bun installation on Windows.")
        #raise typer.Exit() #commented this line
        return #and added this line, now pc init works well on windows

Thanks

**Comment by HellAmbro** [comment]
> Yes, I did pc init (showed "Skipping bun installation on Windows" message) and then pc run (I expected pc run work, but pc run not work -> see attached screen shot) And no initialized files.

Yes i dind't see, i've updated to v0.1.26 and i'm having the same issue, i've commented the line `raise typer.Exit()` and now it's working.
But this is a bug and should be fixed, we just found a workaround.
