### ISSUE TITLE
pc init isn't working (windows)

### ISSUE THREAD

**Issue by TuRagChoi** [pynecone-io/pynecone#883]
When i use "pc init" is is just cming one line:
"Skipping bun installation on windows"
it isn't creating any kind of template or anything, it isn't even counting as an init when i run "pc run", it is just that one line and nothing else

Specifies:
 - Python Version: 3.11.0
 - Pynecone Version: 0.1.26
 - OS: Windows
 - NodeJS is installed
![grafik](https://user-images.githubusercontent.com/81915723/234631824-9b97a052-1974-43e1-8cfd-a939798e8a2d.png)

**Comment by picklelo** [comment]
I just reverted the last release - try use pynecone v0.1.24 and let me know if you have issues.

**Comment by TuRagChoi** [comment]
It worked, thank you
