### ISSUE TITLE
Add Upload to Pynecone

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#90]
Have the ability to upload images and other files.

**Comment by Pranav25191** [comment]
Hi Alek, I tested pynecone locally and got some insights about it. Can I pick up this issue with your guidance?

**Comment by picklelo** [comment]
@Pranav25191 this issue may be a bit tricky, but feel free to get started and we can guide you / collaborate along the way. 

The first thing we need to do is add a new endpoint in [app.py](https://github.com/pynecone-io/pynecone/blob/main/pynecone/app.py) for file uploads. We can probably follow the [FastAPI docs](https://fastapi.tiangolo.com/tutorial/request-files/) here.

Then we need to create the actual upload button and hook it up to the new endpoint we created. Maybe try to add the new endpoint first and we can incrementally get this feature working.

**Comment by Pranav25191** [comment]
@picklelo thanks for your assistance. What I understood is you are telling me to add upload functionality as a new default endpoint initially and test it with fastapi then we can later hook up this endpoint. am I right? if yes I will continue with this.

**Comment by aelise** [comment]
Has this functionality been added @Alek99 ? I looked briefly at v0.1.11 and don't see anything there, and I don't see an upload component described on the website or in the components code. Lmk if I'm missing something, thanks!

**Comment by Alek99** [comment]
Not yet I realized the was a. duplicate story so closed this on the one to watch is here https://github.com/pynecone-io/pynecone/issues/238. Ill mark this as duplicate.
