### ISSUE TITLE
Pynecone official todo app not work in remote server-solved

### ISSUE THREAD

**Issue by automatethem** [pynecone-io/pynecone#904]
**Describe the bug**

Pynecone official todo app works well local.
But not work in remote server (http://52.78.31.107/).

**To Reproduce**
 - Code/Link to Repo:

pc init and pc run official todo app in server.

**Expected behavior**

Expect can add todo item and also delete item but can't

**Screenshots**

![111](https://user-images.githubusercontent.com/108699325/235272664-c8c28b17-310f-42e5-a6dd-91048d0d5313.PNG)

** Specifics (please complete the following information):**
 - Python Version: Python 3.9.13
 - Pynecone Version: 0.1.27
 - OS: ubuntu 20.04 
 - Browser (Optional): chrome
 
**Additional context**

captued chrome console.
browser try to connect to ws://localhost:8000 even though did not run on local pc.
Guess need to connect to ws://52.78.31.107:8000

**Comment by automatethem** [comment]
Solved by adding following line to pcconfig.py
api_url="http://52.78.31.107:8000",

Thanks

**Comment by Alek99** [comment]
Yeah when deploying on a server you need to add the api url, good catch.

**Comment by automatethem** [comment]
> Yeah when deploying on a server you need to add the api url, good catch.

Ok thank you very much for your kind guide!
