### ISSUE TITLE
ComputedVar does not call Var.__getattribute__

### ISSUE THREAD

**Issue by BlackHC** [pynecone-io/pynecone#907]
**Describe the bug**

I have a computed var styled_messaged_thread that returns a custom var of type MessageThread. However, it fails to access attributes correctly. 

```
       State.styled_message_thread.title,
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

AttributeError: 'ComputedVar' object has no attribute 'title'

It seems a possible fix is to change the order of base classes in ComputedVar:

```
-class ComputedVar(property, Var):
+class ComputedVar(Var, property):
```

The property descriptor defines its own __getattribute__ that does not forward to super. This fix requires further validation, however, but works for me.

**To Reproduce**

Create a class that derives from pc.Base and return an instance from a @pc.var in your State.

**Expected behavior**
Access to the ComputedVar's attributes ought to be possible.

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version:  0.1.24
 - OS:  MacOs

**Comment by BlackHC** [comment]
I'm using the following monkey patch in my code now:

```
# Redefine ComputedVar to revert the baseclasses
class _ComputedVar(Var, property):
    """A field with computed getters."""

    @property
    def name(self) -> str:
        """Get the name of the var.

        Returns:
            The name of the var.
        """
        assert self.fget is not None, "Var must have a getter."
        return self.fget.__name__

    @property
    def type_(self):
        """Get the type of the var.

        Returns:
            The type of the var.
        """
        if "return" in self.fget.__annotations__:
            return self.fget.__annotations__["return"]
        return typing.Any

pc.var = _ComputedVar

ComputedVar.register(pc.var)
```

**Comment by ElijahAhianyo** [comment]
Hey @BlackHC, can you confirm if the code below suites your usecase ?

```python
import pynecone as pc


class SomeBaseClass(pc.Base):
    title: str = "title"


class State(pc.State):
    @pc.var
    def some_title(self):
        return SomeBaseClass()


def index() -> pc.Component:
    return pc.center(
        pc.text(State.some_title),
    )


# Add state and page to the app.
app = pc.App(state=State)
app.add_page(index)
app.compile()


```

If so, this behavior is expected as the values of computed vars are derived at runtime. If you return the class attributes directly from the instance(`return SomeBaseClass().title`) that should work, I believe.

**Comment by BlackHC** [comment]
Honestly, you should just fix the base class order, as I have suggested twice already, to fix the issue.

I really don't get why you keep ignoring what I've been pointing out, given that it fixes the issue, and there is an obvious causal reason for why your code is wrong: the current base class order simply prefers `property` over `Var` and thus never calls your implementation of `__getattribute__` in `Var`.

Maybe, you don't know how it works in Python, but see, for example https://stackoverflow.com/questions/64018159/does-order-of-class-bases-in-python-matter

E.g.:
```
class A:
    def foo(self):
        print('class A')
class B:
    def foo(self):
        print('class B')
class C(A, B):
    pass

c = C()
c.foo() # class A
```

> Methods are resolved from left-to-right—e.g., in the example, the foo method comes from class A because A comes before B.

(This is the opposite of how it works in C++ and not very intuitive imo.)

Could you please acknowledge the issue and the bug I've been pointing out to you?

Thanks,
 Andreas

**Comment by Alek99** [comment]
> Honestly, you should just fix the base class order, as I have suggested twice already, to fix the issue.
> 
> I really don't get why you keep ignoring what I've been pointing out, given that it fixes the issue, and there is an obvious causal reason for why your code is wrong: the current base class order simply prefers `property` over `Var` and thus never calls your implementation of `__getattribute__` in `Var`.
> 
> Maybe, you don't know how it works in Python, but see, for example https://stackoverflow.com/questions/64018159/does-order-of-class-bases-in-python-matter
> 
> E.g.:
> 
> ```
> class A:
>     def foo(self):
>         print('class A')
> class B:
>     def foo(self):
>         print('class B')
> class C(A, B):
>     pass
> 
> c = C()
> c.foo() # class A
> ```
> 
>  > Methods are resolved from left-to-right—e.g., in the example, the foo method comes from class A because A comes before B.
> 
> (This is the opposite of how it works in C++ and not very intuitive imo.)
> 
> Could you please acknowledge the issue and the bug I've been pointing out to you?
> 
> Thanks, Andreas

Hi Andreas, I'll try your fix out today. Thanks for the suggestion.

**Comment by Alek99** [comment]
Stuck working on some other issues  /documentation will try this tomorrow

**Comment by BlackHC** [comment]
Thank you!

**Comment by Alek99** [comment]
We merged in a change which switches the order should be out in the next release
