### ISSUE TITLE
behavior of set_[var name] changed after upgrading to  v0.1.27 

### ISSUE THREAD

**Issue by sheldonchiu** [pynecone-io/pynecone#913]
**Describe the bug**

**To Reproduce**
 - Code/Link to Repo:
 ```python
    on_click=[
        EnvState.clear,
        lambda: PaperspaceState.set_env_type("new"),
    ]
```

**Expected behavior**

**Generated code**

With 0.1.24
```javascript
E("base_state.paperspace_state.set_env_type", {value:"existing"})
```

After upgrading to 0.1.27
```javascript
E("base_state.paperspace_state.set_env_type", {value:existing})
```

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:
 - Pynecone Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by ElijahAhianyo** [comment]
Thanks for pointing this out. Will look into this
