### ISSUE TITLE
Modification of Inner Data Strucutre does Trigger State Update 

### ISSUE THREAD

**Issue by Alek99** [pynecone-io/pynecone#924]
**Describe the bug**

Editing an deeply nested field in a ds should trigger a state update for example a ds of a list[dic[str, str]] when updating a dictionary value a state update should occur for the ds and the new  list[dic[str, str]] should we sent back to the client. Similar to how it is done for simple non nested list, dicts, etc.

**Comment by Lendemor** [comment]
Tested with a `list[dict[int, str,]]`

It seems to already be working.
