### ISSUE TITLE
pc.checkbox_group() dosn't work

### ISSUE THREAD

**Issue by jq6l43d1** [pynecone-io/pynecone#931]
**Describe the bug**
pc.checkbox_group() only displays the list that it was given instead of the creating a checkbox for each item in the list.

**To Reproduce**
```
import pynecone as pc

options = ["Option 1", "Option 2", "Option 3"]

class CheckboxState(pc.State):
    pass

def index():
    return pc.vstack(
        pc.checkbox_group(
            options,
        ),
    )

app = pc.App(state=CheckboxState)
app.add_page(index)
app.compile()
```

**Expected behavior**
Each item in the list should have it's own checkbox. That's how it works with radio_group() I think it should work the same way with checkbox_group().

**Screenshots**
![image](https://user-images.githubusercontent.com/110377310/235762233-1f99c203-37bc-4304-8699-6dc75d4c88b0.png)

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 0.1.28
 - OS: Ubuntu 23.04

**Comment by ElijahAhianyo** [comment]
`pc.checkbox_group` typically groups checkboxes so you'd want to use this with `pc.checkbox`. I would change your above to this:

```python
import pynecone as pc

options = ["Option 1", "Option 2", "Option 3"]

class CheckboxState(pc.State):
    pass

def index():
    return pc.vstack(
        pc.checkbox_group(
            pc.foreach(options, lambda x: pc.checkbox(x)),
        ),
    )

app = pc.App(state=CheckboxState)
app.add_page(index)
app.compile()
```

**Comment by jq6l43d1** [comment]
I was just reading the Chakra docs and that's what their examples showed. Thanks!
