### ISSUE TITLE
Allow components to take in other components as props

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#932]
For example so we can pass icons to the [chakra select](https://chakra-ui.com/docs/components/select/usage) 

```python
pc.select(icon=pc.icon("arrow_drop_down"))
```

and it can compile down to 

```js
<Select icon={<MdArrowDropDown />} placeholder='Woohoo! A new icon' />
```

**Comment by iron3oxide** [comment]
Is this a duplicate of #236?

**Comment by picklelo** [comment]
Ah yes good catch! Will close this and add the other one to the sprint.
