### ISSUE TITLE
Several examples in gallery is down

### ISSUE THREAD

**Issue by bjornasm** [pynecone-io/pynecone#943]
**Describe the bug**
Several of the examples in the example gallery is down: 
**To Reproduce**
[Basketball app](https://nba.pynecone.app/) (This site can’t be reachedCheck if there is a typo in nba.pynecone.app.)
[Quiz](https://quiz.pynecone.app/) (Code: NoSuchBucket
Message: The specified bucket does not exist)

Possibly other examples is not working as well. Would be nice to have them up and running!

**Comment by picklelo** [comment]
We've redeployed the gallery apps!
