### ISSUE TITLE
Add color_scheme prop to pc.switch

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#966]
We are missing the `color_scheme` prop in pc.switch: https://chakra-ui.com/docs/components/switch/theming

**Comment by Unknown1934-del** [comment]
Hi, Can I do this ?

**Comment by picklelo** [comment]
@Unknown1934-del yes feel free to take this on. We need to add a prop similar to how we have it in the other form components like [radio](https://github.com/pynecone-io/pynecone/blob/dc2dff9323a7013824c3a73dfea02578b0ecea69/pynecone/components/forms/radio.py#L59)
