### ISSUE TITLE
Support conditional styling

### ISSUE THREAD

**Issue by picklelo** [pynecone-io/pynecone#977]
Currently style props can't use pc.cond - we should support something like

```python
pc.text("hi", color=pc.cond(State.flag, "red", "green"))
```

**Comment by Unknown1934-del** [comment]
Can I work on this?

**Comment by FHU-yezi** [comment]
> Can I work on this?

Sure, feel free to open a PR.

**Comment by picklelo** [comment]
This one may be a bit difficult to get started with - I think @PeterYusuke is working on it so maybe you can collaborate. Also feel free to join our Discord if you need more immediate help with an issue.

**Comment by TaiJuWu** [comment]
```python
pc.text("hi", color=pc.cond(State.flag, "red", "green"))
```
It can work on main right now.
I don't modify any code.

**Comment by picklelo** [comment]
We will update the docs to this
