### ISSUE TITLE
Wrapped React component not working after upgrading to 0.1.29

### ISSUE THREAD

**Issue by jq6l43d1** [pynecone-io/pynecone#987]
**Describe the bug**
I'm using react-confetti on my website. After upgrading from 0.1.28 to 0.1.29 I get an error when the confetti is supposed to drop

**To Reproduce**
Here are the relevant code snippets:

pcconfig.py
```
import pynecone as pc

config = pc.Config(
    app_name="my_website",
    db_url="sqlite:///pynecone.db",
    env=pc.Env.DEV,
    frontend_packages=[
        "react-confetti",
    ],
)
```
confetti.py
```
import pynecone as pc

class Confetti(pc.Component):
    """Confetti component."""

    library = "react-confetti"
    tag = "ReactConfetti"
    width: pc.Var[int]
    height: pc.Var[int]
    recycle: pc.Var[bool]

confetti = Confetti.create
```
Here is a snippit of me calling the component on the page.
```
pc.cond(
    GptState.received,
    pc.cond(
        GptState.confetti_dropped == False,
        confetti(
            height=2160,
            width=3840,
            recycle=False,
        ),
    ),
),
```

**Expected behavior**
The confetti should drop without an error.

**Screenshots**
![image](https://github.com/pynecone-io/pynecone/assets/110377310/4b3eab7a-69ff-4cdd-95cd-55281c0d8050)

** Specifics (please complete the following information):**
 - Python Version: 3.11
 - Pynecone Version: 0.1.29
 - OS: Ubuntu 20.04

**Comment by ElijahAhianyo** [comment]
this should be added to the docs, but for react components with default imports, you need to add an `is_default = True` prop to the component:

```python
import pynecone as pc

class Confetti(pc.Component):
    """Confetti component."""

    library = "react-confetti"
    tag = "ReactConfetti"
    is_default = True
    width: pc.Var[int]
    height: pc.Var[int]
    recycle: pc.Var[bool]
    

confetti = Confetti.create

```

**Comment by jq6l43d1** [comment]
That worked! Thank you so much!
