### ISSUE TITLE
pc.cond should support multiple conditions and logical operators

### ISSUE THREAD

**Issue by jq6l43d1** [pynecone-io/pynecone#994]
I think it would simplify things quite a bit for users if pc.cond supported multiple conditions and logical operators.

For example, instead of:
```
pc.cond(
    condition1,
    pc.cond(
        condition2,
        pc.cond(
            condition3,
            foo,
            bar,
        ),
        bar,
    ),
    bar,
),
```
I think it would be great if we could do it like this:
```
pc.cond(
    condition1 and condition2 and condition3,
    foo,
    bar,
)
```
Support for other logical operators like or and xor should be included too. I think it should be pretty much like a python if statement.

**Comment by Alek99** [comment]
Nice suggestion should be possible will involve some changes to the compiled code.

**Comment by picklelo** [comment]
I'm working on adding a full API reference - but this is already possible -  you have to use the `&` and `|` operators similar to Pandas.

```python
pc.cond(State.cond1 & State.cond2, ...)
pc.cond(State.cond1 | State.cond2, ...)
```

**Comment by picklelo** [comment]
Docs added by @Lendemor
