### ISSUE TITLE
How to check the first radio in radiogroup by default?

### ISSUE THREAD

**Issue by evandeng2009** [pynecone-io/pynecone#998]
**Describe the bug**
I have multiple radios, and need the first one to be checked by default. However radiogroup has no more arguments except `value`. 

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**
Want the first raido to be checked by default

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version: 3.7
 - Pynecone Version: 0.1.28
 - OS: 
 - Browser (Optional):
 
**Additional context**

**Comment by jq6l43d1** [comment]
```
from pcconfig import config

import pynecone as pc

choices = ["a", "b", "c"]

class State(pc.State):

    pass

def index() -> pc.Component:
    return pc.center(
        pc.vstack(
            pc.radio_group(
                choices,
                default_value="a",
                # This also works:
                # default_value=choices[0],
                default_checked=True,
            ),
        ),
        padding_top="10%",
    )

app = pc.App(state=State)
app.add_page(index)
app.compile()
```

**Comment by evandeng2009** [comment]
This does not work, no radio is checked.
![image](https://github.com/pynecone-io/pynecone/assets/11970778/70fcdf74-7bdf-4885-8ee4-8dd7e552ea58)

**Comment by jq6l43d1** [comment]
You need to upgrade to the latest version of pynecone. This won't work on 0.1.28.

**Comment by evandeng2009** [comment]
Thank u Shawn, upgraded to 0.1.29, it works.
